export const EducationToolsData = [
    {
        title: "Course Navigator",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/foundersacademy.svg",
        url: "/pages/education-tools/course-navigator",
        launch_soon: false,
    },
    {
        title: "Politician Insights",
        description: "This tool lets you get a polician insights with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/politician-insights.svg",
        url: "/pages/education-tools/politician-insights",
        launch_soon: true,
    },
    {
        title: "Global Study Visa",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/foundersacademy.svg",
        url: "/pages/education-tools/study-visa",
        launch_soon: true,
    },
    {
        title: "Country Insights",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/country-insights.svg",
        url: "/pages/education-tools/country-insights",
        launch_soon: true,
    },
    {
        title: "Wealth Leaders",
        description: "An assessment that evaluates an entrepreneur's in-depth knowledge and proficiency in specific industries.",
        image: "../../../uniprep-assets/images/icons/wealthy.svg",
        url: "/pages/education-tools/wealthleaderslist",
        launch_soon: false,
    },
    {
        title: "Student Budget Planner",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/foundersacademy.svg",
        url: "/pages/education-tools/student-budget-planner",
        launch_soon: false,
    },
    {
        title: "UniCompare",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/uni-compare.svg",
        url: "/pages/education-tools/uni-compare",
        launch_soon: false,
    },
    {
        title: "Global Edufit",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/global-edufit.svg",
        url: "/pages/education-tools/global-edufit",
        launch_soon: false,
    },
    {
        title: "Loan Comparison Tool",
        description: "This tool lets you get a global travel visa with the help of few easy steps",
        image: "../../../uniprep-assets/images/founderstool/loan-comparison-tool.svg",
        url: "/pages/education-tools/edu-loan-compare",
        launch_soon: false,
    },
    
]