export const marketingAnalysisData = {
    Industry: [
        { "Industry": "D Printing" },
        { "Industry": "Manufacturing" },
        { "Industry": "Prototyping" },
        { "Industry": "Aerospace" },
        { "Industry": "Aviation" },
        { "Industry": "Space" },
        { "Industry": "Agriculture" },
        { "Industry": "Agri-Tech" },
        { "Industry": "Artificial Intelligence" },
        { "Industry": "Robotics" },
        { "Industry": "Automation" },
        { "Industry": "Augmented Reality" },
        { "Industry": "Mixed Reality" },
        { "Industry": "Spatial Computing" },
        { "Industry": "Automotive" },
        { "Industry": "Mobility" },
        { "Industry": "Electric Vehicles" },
        { "Industry": "Autonomous Vehicles" },
        { "Industry": "Self-Driving" },
        { "Industry": "Banking" },
        { "Industry": "Finance" },
        { "Industry": "FinTech" },
        { "Industry": "Beauty" },
        { "Industry": "Skincare" },
        { "Industry": "Personal Care" },
        { "Industry": "Biotechnology" },
        { "Industry": "Genetics" },
        { "Industry": "Life Sciences" },
        { "Industry": "Blockchain" },
        { "Industry": "Cryptocurrency" },
        { "Industry": "Web3" },
        { "Industry": "Consulting" },
        { "Industry": "Construction" },
        { "Industry": "Engineering" },
        { "Industry": "Infrastructure" },
        { "Industry": "Cybersecurity" },
        { "Industry": "Data Privacy" },
        { "Industry": "IT Security" },
        { "Industry": "Drones" },
        { "Industry": "E-commerce" },
        { "Industry": "Retail" },
        { "Industry": "Marketplaces" },
        { "Industry": "EdTech" },
        { "Industry": "Digital Learning" },
        { "Industry": "Education" },
        { "Industry": "Training" },
        { "Industry": "Elderly Care" },
        { "Industry": "Healthcare" },
        { "Industry": "Assisted Living" },
        { "Industry": "Energy" },
        { "Industry": "Utilities" },
        { "Industry": "Power" },
        { "Industry": "Entertainment" },
        { "Industry": "Media" },
        { "Industry": "Broadcasting" },
        { "Industry": "Ethical Business" },
        { "Industry": "Sustainability" },
        { "Industry": "Event Planning" },
        { "Industry": "Weddings" },
        { "Industry": "Fashion" },
        { "Industry": "Apparel" },
        { "Industry": "Textiles" },
        { "Industry": "Fitness" },
        { "Industry": "Wellness" },
        { "Industry": "Food" },
        { "Industry": "Beverage" },
        { "Industry": "Consumer Goods" },
        { "Industry": "Gaming" },
        { "Industry": "Esports" },
        { "Industry": "Healthcare" },
        { "Industry": "Medical" },
        { "Industry": "Pharmaceuticals" },
        { "Industry": "Home Automation" },
        { "Industry": "IoT" },
        { "Industry": "Home Services" },
        { "Industry": "Hospitality" },
        { "Industry": "Tourism" },
        { "Industry": "Human Resources" },
        { "Industry": "Recruitment" },
        { "Industry": "Industrial" },
        { "Industry": "Technology" },
        { "Industry": "IT Services" },
        { "Industry": "Telecommunications" },
        { "Industry": "5G" },
        { "Industry": "Connectivity" },
        { "Industry": "Insurance" },
        { "Industry": "Risk Management" },
        { "Industry": "Legal" },
        { "Industry": "Compliance" },
        { "Industry": "Logistics" },
        { "Industry": "Transportation" },
        { "Industry": "Supply Chain" },
        { "Industry": "Luxury Goods" },
        { "Industry": "Jewelry" },
        { "Industry": "Luxury Travel" },
        { "Industry": "VIP Services" },
        { "Industry": "Metaverse" },
        { "Industry": "Digital Reality" },
        { "Industry": "Pet Care" },
        { "Industry": "Veterinary" },
        { "Industry": "Publishing" },
        { "Industry": "Printing" },
        { "Industry": "Real Estate" },
        { "Industry": "Renewable Energy" },
        { "Industry": "Green Tech" },
        { "Industry": "Smart Homes" },
        { "Industry": "Social Media" },
        { "Industry": "Influencer Marketing" },
        { "Industry": "Space Tourism" },
        { "Industry": "Astrobiology" },
        { "Industry": "Virtual Reality" },
        { "Industry": "Waste Management" },
        { "Industry": "Recycling" },
        { "Industry": "Water Purification" }
    ],

    "Target Audience": [
        { "Target Audience": "Infants & Toddlers (0-3 years)" },
        { "Target Audience": "Children (4-12 years)" },
        { "Target Audience": "Teenagers (13-19 years)" },
        { "Target Audience": "Young Adults (20-35 years)" },
        { "Target Audience": "Middle-Aged Adults (36-55 years)" },
        { "Target Audience": "Seniors (55+ years)" }
    ],

    "Analysis Duration": [
        { "Analysis Duration": "1 Month" },
        { "Analysis Duration": "3 Months" },
        { "Analysis Duration": "6 Months" },
        { "Analysis Duration": "9 Months" },
        { "Analysis Duration": "12 Months" },
        { "Analysis Duration": "18 Months" },
        { "Analysis Duration": "24 Months" },
        { "Analysis Duration": "30 Months" },
        { "Analysis Duration": "36 Months" },
        { "Analysis Duration": "48 Months" },
        { "Analysis Duration": "60 Months" },
        { "Analysis Duration": "72 Months" },
        { "Analysis Duration": "84 Months" },
        { "Analysis Duration": "96 Months" },
        { "Analysis Duration": "108 Months" },
        { "Analysis Duration": "120 Months" }
    ],

    "Product/Service": [
        { "Product/Service": "IT consulting" },
        { "Product/Service": "Dropshipping services" },
        { "Product/Service": "Telemedicine" },
        { "Product/Service": "Financial consulting" },
        { "Product/Service": "Real estate brokerage" },
        { "Product/Service": "Contract manufacturing" },
        { "Product/Service": "Tutoring services" },
        { "Product/Service": "Energy audits" },
        { "Product/Service": "Precision farming" },
        { "Product/Service": "Catering" },
        { "Product/Service": "Video production" },
        { "Product/Service": "Tour planning" },
        { "Product/Service": "Freight forwarding" },
        { "Product/Service": "Car rentals" },
        { "Product/Service": "Architectural consulting" },
        { "Product/Service": "Network security" },
        { "Product/Service": "Personal styling" },
        { "Product/Service": "Salon services" },
        { "Product/Service": "Business legal advisory" },
        { "Product/Service": "Management consulting" },
        { "Product/Service": "Risk assessment" },
        { "Product/Service": "Ethical hacking" },
        { "Product/Service": "AI consulting" },
        { "Product/Service": "Industrial waste management" },
        { "Product/Service": "Esports coaching" },
        { "Product/Service": "Space tourism" },
        { "Product/Service": "Self-publishing" },
        { "Product/Service": "Personal training" },
        { "Product/Service": "Cleaning services" },
        { "Product/Service": "Recruitment services" },
        { "Product/Service": "Crypto investment advisory" },
        { "Product/Service": "Clinical research services" },
        { "Product/Service": "Veterinary clinics" },
        { "Product/Service": "Custom jewelry design" },
        { "Product/Service": "Home automation installation" },
        { "Product/Service": "Wedding planning" },
        { "Product/Service": "Green building consulting" },
        { "Product/Service": "Aerial photography" },
        { "Product/Service": "Textile design consulting" },
        { "Product/Service": "Luxury concierge" },
        { "Product/Service": "AR advertising" },
        { "Product/Service": "Water treatment consulting" },
        { "Product/Service": "Influencer marketing agencies" },
        { "Product/Service": "Sustainability consulting" },
        { "Product/Service": "Self-driving car rental" },
        { "Product/Service": "Cybersecurity services" },
        { "Product/Service": "E-commerce store management" },
        { "Product/Service": "Mental health counseling" },
        { "Product/Service": "Tax advisory" },
        { "Product/Service": "Property appraisal" },
        { "Product/Service": "Industrial automation consulting" },
        { "Product/Service": "Corporate training" },
        { "Product/Service": "Utility management" },
        { "Product/Service": "Agronomy consulting" },
        { "Product/Service": "Cloud kitchen services" },
        { "Product/Service": "Digital marketing" },
        { "Product/Service": "Concierge services" },
        { "Product/Service": "EV charging station installation" },
        { "Product/Service": "Construction project management" },
        { "Product/Service": "Cloud telephony" },
        { "Product/Service": "Fashion rental" },
        { "Product/Service": "Spa treatments" },
        { "Product/Service": "Intellectual property services" },
        { "Product/Service": "HR outsourcing" },
        { "Product/Service": "Claims processing" },
        { "Product/Service": "Data protection consulting" },
        { "Product/Service": "AI integration services" },
        { "Product/Service": "Recycling consulting" },
        { "Product/Service": "Game streaming services" },
        { "Product/Service": "Aerospace engineering consulting" },
        { "Product/Service": "Print-on-demand" },
        { "Product/Service": "Online fitness coaching" },
        { "Product/Service": "Plumbing & electrical repairs" },
        { "Product/Service": "Resume writing" },
        { "Product/Service": "Blockchain development" },
        { "Product/Service": "Bioinformatics consulting" },
        { "Product/Service": "Dog training" },
        { "Product/Service": "Personal shopping" },
        { "Product/Service": "IoT consulting" },
        { "Product/Service": "Event coordination" },
        { "Product/Service": "Carbon credit services" },
        { "Product/Service": "Drone delivery" },
        { "Product/Service": "Fabric testing services" },
        { "Product/Service": "VIP travel planning" },
        { "Product/Service": "VR game development" },
        { "Product/Service": "Home nursing" },
        { "Product/Service": "AR-based gaming" },
        { "Product/Service": "On-demand 3D printing" },
        { "Product/Service": "Purification system installation" },
        { "Product/Service": "Brand partnerships" },
        { "Product/Service": "Ethical sourcing advisory" },
        { "Product/Service": "Astrobiology research" },
        { "Product/Service": "AI navigation systems" },
        { "Product/Service": "Web & App development" },
        { "Product/Service": "Home healthcare services" },
        { "Product/Service": "Wealth management" },
        { "Product/Service": "Interior design consulting" },
        { "Product/Service": "Supply chain optimization" },
        { "Product/Service": "School management services" },
        { "Product/Service": "Renewable energy consulting" },
        { "Product/Service": "Soil testing services" },
        { "Product/Service": "Meal subscription plans" },
        { "Product/Service": "Influencer management" },
        { "Product/Service": "Airbnb management" },
        { "Product/Service": "Warehouse automation" },
        { "Product/Service": "Fleet management" },
        { "Product/Service": "Civil engineering services" },
        { "Product/Service": "Telecom consulting" },
        { "Product/Service": "Clothing alteration services" },
        { "Product/Service": "Personal grooming" },
        { "Product/Service": "Litigation consulting" },
        { "Product/Service": "Business strategy services" },
        { "Product/Service": "Insurance brokerage" },
        { "Product/Service": "Security training" },
        { "Product/Service": "Data annotation" },
        { "Product/Service": "Carbon footprint analysis" },
        { "Product/Service": "Competitive gaming events" },
        { "Product/Service": "Graphic design services" },
        { "Product/Service": "Wellness retreats" },
        { "Product/Service": "Home renovation" },
        { "Product/Service": "Employee training programs" },
        { "Product/Service": "Smart contract auditing" },
        { "Product/Service": "DNA testing" },
        { "Product/Service": "Pet grooming services" },
        { "Product/Service": "Concierge services" },
        { "Product/Service": "Security system setup" },
        { "Product/Service": "Corporate event management" },
        { "Product/Service": "Energy audits" },
        { "Product/Service": "Mapping & surveying" },
        { "Product/Service": "Custom tailoring" },
        { "Product/Service": "Personalized vacation packages" },
        { "Product/Service": "Metaverse consulting" },
        { "Product/Service": "Senior activity programs" },
        { "Product/Service": "Virtual property tours" },
        { "Product/Service": "Custom design services" },
        { "Product/Service": "Wastewater management" },
        { "Product/Service": "Content strategy consulting" },
        { "Product/Service": "Carbon neutrality certification" },
        { "Product/Service": "Autonomous fleet management" }
    ],

    "Model": [
        { "Model": "B2B (Business-to-Business)" },
        { "Model": "B2C (Business-to-Consumer)" },
        { "Model": "B2B2C (Business-to-Business-to-Consumer)" },
        { "Model": "C2C (Consumer-to-Consumer)" },
        { "Model": "C2B (Consumer-to-Business)" },
        { "Model": "P2P (Peer-to-Peer)" },
        { "Model": "DTC (Direct-to-Consumer)" },
        { "Model": "B2G (Business-to-Government)" },
        { "Model": "G2B (Government-to-Business)" },
        { "Model": "G2C (Government-to-Consumer)" },
        { "Model": "C2G (Consumer-to-Government)" }
    ],

    "Sales Channels": [
        { "Sales Channel": "Direct Sales" },
        { "Sales Channel": "E-commerce" },
        { "Sales Channel": "Retail Stores" },
        { "Sales Channel": "Wholesale" },
        { "Sales Channel": "Dropshipping" },
        { "Sales Channel": "Marketplaces" },
        { "Sales Channel": "Social Media Commerce" },
        { "Sales Channel": "Affiliate Marketing" },
        { "Sales Channel": "Subscription Model" },
        { "Sales Channel": "Telemarketing & Cold Calling" },
        { "Sales Channel": "Resellers & Distributors" },
        { "Sales Channel": "Pop-Up Shops & Events" },
        { "Sales Channel": "Franchise Model" },
        { "Sales Channel": "Catalog & Mail Order Sales" },
        { "Sales Channel": "Wholesale Clubs & Memberships" },
        { "Sales Channel": "Door-to-Door Sales" },
        { "Sales Channel": "Live Streaming Sales" },
        { "Sales Channel": "Corporate & Enterprise Sales" },
        { "Sales Channel": "Partner & Referral Sales" },
        { "Sales Channel": "Mobile Apps & In-App Purchases" },
        { "Sales Channel": "Kiosks & Vending Machines" }
    ],

    "Revenue Streams": [
        { "Revenue Stream": "Product Sales" },
        { "Revenue Stream": "Service Fees" },
        { "Revenue Stream": "Subscription Revenue" },
        { "Revenue Stream": "Licensing Fees" },
        { "Revenue Stream": "Advertising Revenue" },
        { "Revenue Stream": "Affiliate Marketing" },
        { "Revenue Stream": "Commission-based Revenue" },
        { "Revenue Stream": "Transaction Fees" },
        { "Revenue Stream": "Sponsorship Deals" },
        { "Revenue Stream": "Membership Fees" },
        { "Revenue Stream": "Royalties" },
        { "Revenue Stream": "Consulting Fees" },
        { "Revenue Stream": "Pay-per-Use Revenue" },
        { "Revenue Stream": "Rental Income" },
        { "Revenue Stream": "Franchising Fees" },
        { "Revenue Stream": "Resale Revenue" },
        { "Revenue Stream": "Lead Generation Fees" },
        { "Revenue Stream": "Crowdfunding" },
        { "Revenue Stream": "Donations" },
        { "Revenue Stream": "Government Grants" }
    ],

    "Competitor Analysis Focus": [
        { "Focus": "Market Positioning" },
        { "Focus": "Target Audience" },
        { "Focus": "Product/Service Offerings" },
        { "Focus": "Pricing Strategy" },
        { "Focus": "Revenue Streams" },
        { "Focus": "Marketing & Branding" },
        { "Focus": "Sales Channels" },
        { "Focus": "Customer Base & Retention" },
        { "Focus": "Competitive Advantage" },
        { "Focus": "Weaknesses & Gaps" },
        { "Focus": "Market Share" },
        { "Focus": "Geographical Presence" },
        { "Focus": "Technology & Innovation" },
        { "Focus": "Customer Reviews & Satisfaction" },
        { "Focus": "Supply Chain & Operations" },
        { "Focus": "Financial Performance" },
        { "Focus": "Business Growth & Expansion" },
        { "Focus": "Employee Strength & Culture" },
        { "Focus": "Threats & Risks" }
    ],

    "Market Forecast": [
        { "Forecast": "Weekly" },
        { "Forecast": "Bi-Weekly" },
        { "Forecast": "Monthly" },
        { "Forecast": "Quarterly" },
        { "Forecast": "Half-Yearly" },
        { "Forecast": "Annual" },
        { "Forecast": "Biennial" },
        { "Forecast": "Triennial" },
        { "Forecast": "Five-Year Forecast" },
        { "Forecast": "Ten-Year Forecast" },
        { "Forecast": "Short-Term (0-6 Months)" },
        { "Forecast": "Medium-Term (1-3 Years)" },
        { "Forecast": "Long-Term (3+ Years)" },
        { "Forecast": "Fiscal Year Forecast" }
    ]
}