export const startupDropdownData = {
    Industry: [
        { "Industry": "D Printing" },
        { "Industry": "Manufacturing" },
        { "Industry": "Prototyping" },
        { "Industry": "Aerospace" },
        { "Industry": "Aviation" },
        { "Industry": "Space" },
        { "Industry": "Agriculture" },
        { "Industry": "Agri-Tech" },
        { "Industry": "Artificial Intelligence" },
        { "Industry": "Robotics" },
        { "Industry": "Automation" },
        { "Industry": "Augmented Reality" },
        { "Industry": "Mixed Reality" },
        { "Industry": "Spatial Computing" },
        { "Industry": "Automotive" },
        { "Industry": "Mobility" },
        { "Industry": "Electric Vehicles" },
        { "Industry": "Autonomous Vehicles" },
        { "Industry": "Self-Driving" },
        { "Industry": "Banking" },
        { "Industry": "Finance" },
        { "Industry": "FinTech" },
        { "Industry": "Beauty" },
        { "Industry": "Skincare" },
        { "Industry": "Personal Care" },
        { "Industry": "Biotechnology" },
        { "Industry": "Genetics" },
        { "Industry": "Life Sciences" },
        { "Industry": "Blockchain" },
        { "Industry": "Cryptocurrency" },
        { "Industry": "Web3" },
        { "Industry": "Consulting" },
        { "Industry": "Construction" },
        { "Industry": "Engineering" },
        { "Industry": "Infrastructure" },
        { "Industry": "Cybersecurity" },
        { "Industry": "Data Privacy" },
        { "Industry": "IT Security" },
        { "Industry": "Drones" },
        { "Industry": "E-commerce" },
        { "Industry": "Retail" },
        { "Industry": "Marketplaces" },
        { "Industry": "EdTech" },
        { "Industry": "Digital Learning" },
        { "Industry": "Education" },
        { "Industry": "Training" },
        { "Industry": "Elderly Care" },
        { "Industry": "Healthcare" },
        { "Industry": "Assisted Living" },
        { "Industry": "Energy" },
        { "Industry": "Utilities" },
        { "Industry": "Power" },
        { "Industry": "Entertainment" },
        { "Industry": "Media" },
        { "Industry": "Broadcasting" },
        { "Industry": "Ethical Business" },
        { "Industry": "Sustainability" },
        { "Industry": "Event Planning" },
        { "Industry": "Weddings" },
        { "Industry": "Fashion" },
        { "Industry": "Apparel" },
        { "Industry": "Textiles" },
        { "Industry": "Fitness" },
        { "Industry": "Wellness" },
        { "Industry": "Food" },
        { "Industry": "Beverage" },
        { "Industry": "Consumer Goods" },
        { "Industry": "Gaming" },
        { "Industry": "Esports" },
        { "Industry": "Healthcare" },
        { "Industry": "Medical" },
        { "Industry": "Pharmaceuticals" },
        { "Industry": "Home Automation" },
        { "Industry": "IoT" },
        { "Industry": "Home Services" },
        { "Industry": "Hospitality" },
        { "Industry": "Tourism" },
        { "Industry": "Human Resources" },
        { "Industry": "Recruitment" },
        { "Industry": "Industrial" },
        { "Industry": "Technology" },
        { "Industry": "IT Services" },
        { "Industry": "Telecommunications" },
        { "Industry": "5G" },
        { "Industry": "Connectivity" },
        { "Industry": "Insurance" },
        { "Industry": "Risk Management" },
        { "Industry": "Legal" },
        { "Industry": "Compliance" },
        { "Industry": "Logistics" },
        { "Industry": "Transportation" },
        { "Industry": "Supply Chain" },
        { "Industry": "Luxury Goods" },
        { "Industry": "Jewelry" },
        { "Industry": "Luxury Travel" },
        { "Industry": "VIP Services" },
        { "Industry": "Metaverse" },
        { "Industry": "Digital Reality" },
        { "Industry": "Pet Care" },
        { "Industry": "Veterinary" },
        { "Industry": "Publishing" },
        { "Industry": "Printing" },
        { "Industry": "Real Estate" },
        { "Industry": "Renewable Energy" },
        { "Industry": "Green Tech" },
        { "Industry": "Smart Homes" },
        { "Industry": "Social Media" },
        { "Industry": "Influencer Marketing" },
        { "Industry": "Space Tourism" },
        { "Industry": "Astrobiology" },
        { "Industry": "Virtual Reality" },
        { "Industry": "Waste Management" },
        { "Industry": "Recycling" },
        { "Industry": "Water Purification" },
        { "Industry": "Finland" }
    ],
    "Startup Stage": [
        { name: "Ideation Stage" },
        { name: "Concept Development & Research" },
        { name: "Market Validation & Feasibility Analysis" },
        { name: "Pre-Seed Stage (Initial Funding & Prototyping)" },
        { name: "Seed Stage (MVP Development & Early Customers)" },
        { name: "Product Market Fit & Refinement" },
        { name: "Early Stage Startup (Launch & Market Entry)" },
        { name: "Revenue Generation & Customer Acquisition" },
        { name: "Growth Stage (Scaling & Expansion)" },
        { name: "Series A & B Funding Phase (Scale-up Growth & Market Expansion)" },
        { name: "Scaling Operations & Market Penetration" },
        { name: "Maturity Stage (Sustainable Growth & Profitability)" },
        { name: "Late Stage Startup (Market Leadership & Stability)" },
        { name: "Exit Planning (IPO, Acquisition, or Mergers)" },
        { name: "Exit Strategy (Final Stage & Investor Returns)" }
    ],
    "Location": [
        { name: "In Database (Location Only)" }
    ],
    "Team Size": [
        { name: "Solo Entrepreneur (1 person)" },
        { name: "Small Team (2-5 people)" },
        { name: "Startup Team (6-10 people)" },
        { name: "Growing Team (11-20 people)" },
        { name: "Medium-Sized Team (21-50 people)" },
        { name: "Large Team (51-100 people)" },
        { name: "Enterprise Team (101-500 people)" },
        { name: "Corporate Team (501-1000 people)" },
        { name: "Global Organization (1000+ people)" },
        { name: "Remote/Full Remote/Distributed Workforce" },
        { name: "Hybrid Team (Office + Remote)" },
        { name: "Project Based Team (Temporary or Contract Workers)" }
    ],
    "Key expenses": [
        { name: "Operational Expenses ( Rent, salaries, insurance, legal fees )" },
        { name: "Product Development ( Software, cloud hosting, )" },
        { name: "Marketing & Sales ( Ads, PR, customer acquisition )" },
        { name: "Financial Costs ( Bank fees, loan repayments )" },
        { name: "Growth & Scaling ( Hiring, training, expansion costs )" },
        { name: "Miscellaneous ( Office supplies, team perks, emergency costs )" }
    ],
    "Capital Investment": [
        { name: "Input Field ( with 0 Digits) [Currency]" }
    ],
    "Revenue Model": [
        { name: "Subscription Based Model" },
        { name: "One-Time Setup Fee" },
        { name: "Premium Model" },
        { name: "Pay-Per-Use" },
        { name: "Commission-Based Model" },
        { name: "Advertising Revenue" },
        { name: "Affiliate Marketing" },
        { name: "Licensing Fees" },
        { name: "Product Sales" },
        { name: "White Labeling" },
        { name: "Franchise Model" },
        { name: "Brokerage Fees" },
        { name: "Leasing & Renting" },
        { name: "Crowdfunding & Donations" },
        { name: "Data Monetization" },
        { name: "Membership Fees" },
        { name: "Service Fees" },
        { name: "Consulting & Coaching" },
        { name: "Revenue Sharing" },
        { name: "Microtransactions" },
        { name: "Pay What You Want" },
        { name: "Freight & Logistics Charges" },
        { name: "Event Ticket Sales" },
        { name: "API Monetization" },
        { name: "Usage-Based Insurance" }
    ],
    "Operating Expenses in $/month": [
        { name: "Input Field ( with 0 Digits) [Currency]" }
    ],
    "Sales & Marketing Budget in $/month": [
        { name: "Input Field ( with 0 Digits) [Currency]" }
    ],
    "Expense Estimation": [
        { name: "1 Month (Monthly)" },
        { name: "3 Months (Quarterly)" },
        { name: "6 Months (Half-Yearly / Semi-Annual)" },
        { name: "9 Months (Three-Quarterly)" },
        { name: "12 Months (Annual / Yearly)" },
        { name: "18 Months (1.5 Years)" },
        { name: "24 Months (2 Years)" },
        { name: "36 Months (3 Years)" },
        { name: "48 Months (4 Years)" },
        { name: "60 Months (5 Years)" },
        { name: "72 Months (6 Years)" },
        { name: "84 Months (7 Years)" },
        { name: "96 Months (8 Years)" },
        { name: "108 Months (9 Years)" },
        { name: "120 Months (10 Years)" }
    ]
};
