export const businessAdvisor = {
  "industry": [
    { "industry": "Technology & IT Services" },
    { "industry": "E-commerce & Retail" },
    { "industry": "Healthcare & Pharmaceuticals" },
    { "industry": "Finance & FinTech" },
    { "industry": "Real Estate & Property" },
    { "industry": "Manufacturing" },
    { "industry": "Education & EdTech" },
    { "industry": "Energy & Utilities" },
    { "industry": "Agriculture & Agribusiness" },
    { "industry": "Food & Beverage" },
    { "industry": "Entertainment & Media" },
    { "industry": "Hospitality & Tourism" },
    { "industry": "Transportation & Logistics" },
    { "industry": "Automotive & EV Industry" },
    { "industry": "Construction & Infrastructure" },
    { "industry": "Telecommunications" },
    { "industry": "Fashion & Apparel" },
    { "industry": "Beauty & Personal Care" },
    { "industry": "Legal Services" },
    { "industry": "Consumer & Business Services" },
    { "industry": "Insurance" },
    { "industry": "Cybersecurity" },
    { "industry": "Artificial Intelligence (AI)" },
    { "industry": "Waste Management & Recycling" },
    { "industry": "Gaming & Entertainment" },
    { "industry": "Aerospace & Space Technology" },
    { "industry": "Printing & Publishing" },
    { "industry": "Fitness & Wellness" },
    { "industry": "Home Services" },
    { "industry": "Human Resources & Staffing" },
    { "industry": "Blockchain & Cryptocurrency" },
    { "industry": "Biotechnology & Life Sciences" },
    { "industry": "Pet Care & Veterinary Services" },
    { "industry": "Luxury Goods & Fashion" },
    { "industry": "Home Automation & Smart Tech" },
    { "industry": "Event Management & Wedding Planning" },
    { "industry": "Renewable Energy & Green Tech" },
    { "industry": "Drones & UAV Technology" },
    { "industry": "Textile & Fabric Manufacturing" },
    { "industry": "Luxury Travel & VIP Services" },
    { "industry": "Metaverse & Virtual Reality (VR)" },
    { "industry": "Elderly Care & Assisted Living" },
    { "industry": "Augmented Reality (AR)" },
    { "industry": "3D Printing & Additive Manufacturing" },
    { "industry": "Water Purification & Supply" },
    { "industry": "Social Media & Influencer Marketing" },
    { "industry": "Green & Sustainable Business" },
    { "industry": "Sports Science & Technology" },
    { "industry": "Self-Driving & Autonomous Tech" }
  ],
  "businessGoals": [
    { "goal": "Revenue Growth" },
    { "goal": "Profitability" },
    { "goal": "Expense Reduction" },
    { "goal": "Funding & Investment" },
    { "goal": "Debt Management" },
    { "goal": "Market Dominance" },
    { "goal": "Product Development" },
    { "goal": "Customer Base Growth" },
    { "goal": "Franchising & Partnerships" },
    { "goal": "International Expansion" },
    { "goal": "Customer Satisfaction" },
    { "goal": "Brand Awareness" },
    { "goal": "Market Share Growth" },
    { "goal": "Loyalty & Retention" },
    { "goal": "Competitive Advantage" },
    { "goal": "Efficiency Improvement" },
    { "goal": "Supply Chain Optimization" },
    { "goal": "Sustainability & Eco-Friendliness" },
    { "goal": "Employee Productivity" },
    { "goal": "Innovation & Technology Adoption" },
    { "goal": "Lead Generation" },
    { "goal": "Conversion Rate Optimization" },
    { "goal": "Advertising & Promotion" },
    { "goal": "Social Media Engagement" },
    { "goal": "SEO & Content Marketing" }
  ],
  "challenges": [
    { "challenge": "Regulatory Issues" },
    { "challenge": "Funding Constraints" },
    { "challenge": "Market Competition" },
    { "challenge": "Poor Infrastructure" },
    { "challenge": "Skill Shortage" },
    { "challenge": "Digital Transition" },
    { "challenge": "Bureaucracy Delays" },
    { "challenge": "Corruption Risks" },
    { "challenge": "Brand Trust" },
    { "challenge": "Market Volatility" },
    { "challenge": "IP Protection" },
    { "challenge": "Tax Position" },
    { "challenge": "Slow Approvals" },
    { "challenge": "Talent Difficulty" },
    { "challenge": "Consumer Trends" },
    { "challenge": "Global Access" },
    { "challenge": "Supply Disruptions" },
    { "challenge": "Sustainability Issues" },
    { "challenge": "Customer Retention" },
    { "challenge": "Industry Collaboration" },
    { "challenge": "Cybersecurity Threat" },
    { "challenge": "Legal Complexities" },
    { "challenge": "Inflation Impact" },
    { "challenge": "Technology Costs" },
    { "challenge": "Innovation Gaps" }
  ],
  "targetAudience": [
    { "audience": "Children (0-12 years)" },
    { "audience": "Teenagers (13-19 years)" },
    { "audience": "Young Adults (20-35)" },
    { "audience": "Middle-Aged Adults" },
    { "audience": "Seniors (55+ years)" },
    { "audience": "Low-Income Consumers" },
    { "audience": "Middle-Class Consumers" },
    { "audience": "High-Income Consumers" },
    { "audience": "Ultra-High Net Worth" },
    { "audience": "Men" },
    { "audience": "Women" },
    { "audience": "Parents" },
    { "audience": "Students" },
    { "audience": "Working Professionals" },
    { "audience": "Fitness Enthusiasts" },
    { "audience": "Tech Lovers" },
    { "audience": "Fashion & Beauty Seekers" },
    { "audience": "Local Community" },
    { "audience": "Governmentals" },
    { "audience": "Pet Owners" },
    { "audience": "Property Buyers" },
    { "audience": "Loyal Customers" },
    { "audience": "Discount Seekers" },
    { "audience": "Quality-Oriented Buyers" },
    { "audience": "Tech-Savvy Shoppers" }
  ],
  "strategies": [
    { "strategy": "Cost Optimization" },
    { "strategy": "Cost Reduction" },
    { "strategy": "Loyalty Programs" },
    { "strategy": "Digital Marketing" },
    { "strategy": "Geographic Diversification" },
    { "strategy": "Process Automation" },
    { "strategy": "Performance Incentives" },
    { "strategy": "R&D Investment" },
    { "strategy": "Quality Improvement" },
    { "strategy": "Unique Value" },
    { "strategy": "Content Marketing" },
    { "strategy": "Budget Planning" },
    { "strategy": "Logistics Optimization" },
    { "strategy": "Green Initiatives" },
    { "strategy": "Contingency Planning" },
    { "strategy": "Talent Acquisition" },
    { "strategy": "Community Engagement" },
    { "strategy": "Policy Adherence" },
    { "strategy": "Pricing Optimization" },
    { "strategy": "Expense Management" },
    { "strategy": "Customer Experience" },
    { "strategy": "Influencer Marketing" },
    { "strategy": "Franchise Model" },
    { "strategy": "Workflow Automation" },
    { "strategy": "Skill Development" },
    { "strategy": "Product Differentiation" },
    { "strategy": "Service Excellence" },
    { "strategy": "Niche Focus" },
    { "strategy": "SEO Strategies" },
    { "strategy": "Cash Flow Control" },
    { "strategy": "Vendor Management" },
    { "strategy": "Renewable Solutions" },
    { "strategy": "Crisis Prevention" },
    { "strategy": "Leadership Development" },
    { "strategy": "Ethical Practices" },
    { "strategy": "Regulatory Adherence" },
    { "strategy": "Persuasive Copywriting" },
    { "strategy": "Cross-Functional Teams" },
    { "strategy": "Brand Storytelling" },
    { "strategy": "Referral Programs" },
    { "strategy": "Strategic Alliances" },
    { "strategy": "User Feedback" },
    { "strategy": "Lean Operations" },
    { "strategy": "Task Prioritization" },
    { "strategy": "Data Analytics" },
    { "strategy": "Workplace Culture" },
    { "strategy": "Rapid Response" }
  ],
  "budgetGoals": [
    { "goal": "₹1,00,000 - ₹2,00,000" },
    { "goal": "₹75,000 - ₹1,00,000" },
    { "goal": "₹1,50,000 - ₹2,50,000" },
    { "goal": "₹1,50,000 - ₹2,00,000" },
    { "goal": "₹1,75,000 - ₹2,80,000" },
    { "goal": "₹2,00,000 - ₹3,00,000" },
    { "goal": "₹2,40,000 - ₹3,60,000" },
    { "goal": "₹75,000 - ₹90,000" },
    { "goal": "₹60,000 - ₹77,500" },
    { "goal": "₹75,000 - ₹1,00,000" },
    { "goal": "₹1,00,000 - ₹1,50,000" },
    { "goal": "₹1,50,000 - ₹2,00,000" },
    { "goal": "₹2,00,000 - ₹2,50,000" },
    { "goal": "₹2,50,000 - ₹3,00,000" },
    { "goal": "₹3,00,000 - ₹3,50,000" },
    { "goal": "₹4,00,000 - ₹4,50,000" },
    { "goal": "₹4,50,000 - ₹5,00,000" },
    { "goal": "₹5,50,000 - ₹6,00,000" },
    { "goal": "₹5,00,000 - ₹5,50,000" },
    { "goal": "₹5,50,000 - ₹6,00,000" },
    { "goal": "₹7,50,000 - ₹8,00,000" },
    { "goal": "₹6,50,000 - ₹7,00,000" },
    { "goal": "₹7,00,000 - ₹8,00,000" },
    { "goal": "₹9,00,000 - ₹9,50,000" },
    { "goal": "₹9,00,000 - ₹10,00,000" }
  ],
  "timeDuration": [
    { "duration": 6 },
    { "duration": 12 },
    { "duration": 18 },
    { "duration": 24 },
    { "duration": 30 },
    { "duration": 36 },
    { "duration": 48 }
  ]
}