export const businessAdvisor = {
  Industry: [
    { "Industry": "D Printing" },
    { "Industry": "Manufacturing" },
    { "Industry": "Prototyping" },
    { "Industry": "Aerospace" },
    { "Industry": "Aviation" },
    { "Industry": "Space" },
    { "Industry": "Agriculture" },
    { "Industry": "Agri-Tech" },
    { "Industry": "Artificial Intelligence" },
    { "Industry": "Robotics" },
    { "Industry": "Automation" },
    { "Industry": "Augmented Reality" },
    { "Industry": "Mixed Reality" },
    { "Industry": "Spatial Computing" },
    { "Industry": "Automotive" },
    { "Industry": "Mobility" },
    { "Industry": "Electric Vehicles" },
    { "Industry": "Autonomous Vehicles" },
    { "Industry": "Self-Driving" },
    { "Industry": "Banking" },
    { "Industry": "Finance" },
    { "Industry": "FinTech" },
    { "Industry": "Beauty" },
    { "Industry": "Skincare" },
    { "Industry": "Personal Care" },
    { "Industry": "Biotechnology" },
    { "Industry": "Genetics" },
    { "Industry": "Life Sciences" },
    { "Industry": "Blockchain" },
    { "Industry": "Cryptocurrency" },
    { "Industry": "Web3" },
    { "Industry": "Consulting" },
    { "Industry": "Construction" },
    { "Industry": "Engineering" },
    { "Industry": "Infrastructure" },
    { "Industry": "Cybersecurity" },
    { "Industry": "Data Privacy" },
    { "Industry": "IT Security" },
    { "Industry": "Drones" },
    { "Industry": "E-commerce" },
    { "Industry": "Retail" },
    { "Industry": "Marketplaces" },
    { "Industry": "EdTech" },
    { "Industry": "Digital Learning" },
    { "Industry": "Education" },
    { "Industry": "Training" },
    { "Industry": "Elderly Care" },
    { "Industry": "Healthcare" },
    { "Industry": "Assisted Living" },
    { "Industry": "Energy" },
    { "Industry": "Utilities" },
    { "Industry": "Power" },
    { "Industry": "Entertainment" },
    { "Industry": "Media" },
    { "Industry": "Broadcasting" },
    { "Industry": "Ethical Business" },
    { "Industry": "Sustainability" },
    { "Industry": "Event Planning" },
    { "Industry": "Weddings" },
    { "Industry": "Fashion" },
    { "Industry": "Apparel" },
    { "Industry": "Textiles" },
    { "Industry": "Fitness" },
    { "Industry": "Wellness" },
    { "Industry": "Food" },
    { "Industry": "Beverage" },
    { "Industry": "Consumer Goods" },
    { "Industry": "Gaming" },
    { "Industry": "Esports" },
    { "Industry": "Healthcare" },
    { "Industry": "Medical" },
    { "Industry": "Pharmaceuticals" },
    { "Industry": "Home Automation" },
    { "Industry": "IoT" },
    { "Industry": "Home Services" },
    { "Industry": "Hospitality" },
    { "Industry": "Tourism" },
    { "Industry": "Human Resources" },
    { "Industry": "Recruitment" },
    { "Industry": "Industrial" },
    { "Industry": "Technology" },
    { "Industry": "IT Services" },
    { "Industry": "Telecommunications" },
    { "Industry": "5G" },
    { "Industry": "Connectivity" },
    { "Industry": "Insurance" },
    { "Industry": "Risk Management" },
    { "Industry": "Legal" },
    { "Industry": "Compliance" },
    { "Industry": "Logistics" },
    { "Industry": "Transportation" },
    { "Industry": "Supply Chain" },
    { "Industry": "Luxury Goods" },
    { "Industry": "Jewelry" },
    { "Industry": "Luxury Travel" },
    { "Industry": "VIP Services" },
    { "Industry": "Metaverse" },
    { "Industry": "Digital Reality" },
    { "Industry": "Pet Care" },
    { "Industry": "Veterinary" },
    { "Industry": "Publishing" },
    { "Industry": "Printing" },
    { "Industry": "Real Estate" },
    { "Industry": "Renewable Energy" },
    { "Industry": "Green Tech" },
    { "Industry": "Smart Homes" },
    { "Industry": "Social Media" },
    { "Industry": "Influencer Marketing" },
    { "Industry": "Space Tourism" },
    { "Industry": "Astrobiology" },
    { "Industry": "Virtual Reality" },
    { "Industry": "Waste Management" },
    { "Industry": "Recycling" },
    { "Industry": "Water Purification" },
    { "Industry": "Finland" }
  ],
  "businessGoals": [
    { "goal": "Revenue Growth" },
    { "goal": "Profitability" },
    { "goal": "Expense Reduction" },
    { "goal": "Funding & Investment" },
    { "goal": "Debt Management" },
    { "goal": "Market Dominance" },
    { "goal": "Product Development" },
    { "goal": "Customer Base Growth" },
    { "goal": "Franchising & Partnerships" },
    { "goal": "International Expansion" },
    { "goal": "Customer Satisfaction" },
    { "goal": "Brand Awareness" },
    { "goal": "Market Share Growth" },
    { "goal": "Loyalty & Retention" },
    { "goal": "Competitive Advantage" },
    { "goal": "Efficiency Improvement" },
    { "goal": "Supply Chain Optimization" },
    { "goal": "Sustainability & Eco-Friendliness" },
    { "goal": "Employee Productivity" },
    { "goal": "Innovation & Technology Adoption" },
    { "goal": "Lead Generation" },
    { "goal": "Conversion Rate Optimization" },
    { "goal": "Advertising & Promotion" },
    { "goal": "Social Media Engagement" },
    { "goal": "SEO & Content Marketing" }
  ],
  "challenges": [
    { "challenge": "Regulatory Issues" },
    { "challenge": "Funding Constraints" },
    { "challenge": "Market Competition" },
    { "challenge": "Poor Infrastructure" },
    { "challenge": "Skill Shortage" },
    { "challenge": "Digital Transition" },
    { "challenge": "Bureaucracy Delays" },
    { "challenge": "Corruption Risks" },
    { "challenge": "Brand Trust" },
    { "challenge": "Market Volatility" },
    { "challenge": "IP Protection" },
    { "challenge": "Tax Position" },
    { "challenge": "Slow Approvals" },
    { "challenge": "Talent Difficulty" },
    { "challenge": "Consumer Trends" },
    { "challenge": "Global Access" },
    { "challenge": "Supply Disruptions" },
    { "challenge": "Sustainability Issues" },
    { "challenge": "Customer Retention" },
    { "challenge": "Industry Collaboration" },
    { "challenge": "Cybersecurity Threat" },
    { "challenge": "Legal Complexities" },
    { "challenge": "Inflation Impact" },
    { "challenge": "Technology Costs" },
    { "challenge": "Innovation Gaps" }
  ],
  "targetAudience": [
    { "audience": "Children (0-12 years)" },
    { "audience": "Teenagers (13-19 years)" },
    { "audience": "Young Adults (20-35)" },
    { "audience": "Middle-Aged Adults" },
    { "audience": "Seniors (55+ years)" },
    { "audience": "Low-Income Consumers" },
    { "audience": "Middle-Class Consumers" },
    { "audience": "High-Income Consumers" },
    { "audience": "Ultra-High Net Worth" },
    { "audience": "Men" },
    { "audience": "Women" },
    { "audience": "Parents" },
    { "audience": "Students" },
    { "audience": "Working Professionals" },
    { "audience": "Fitness Enthusiasts" },
    { "audience": "Tech Lovers" },
    { "audience": "Fashion & Beauty Seekers" },
    { "audience": "Local Community" },
    { "audience": "Governmentals" },
    { "audience": "Pet Owners" },
    { "audience": "Property Buyers" },
    { "audience": "Loyal Customers" },
    { "audience": "Discount Seekers" },
    { "audience": "Quality-Oriented Buyers" },
    { "audience": "Tech-Savvy Shoppers" }
  ],
  "strategies": [
    { "strategy": "Sales Optimization" },
    { "strategy": "Cost Reduction" },
    { "strategy": "Loyalty Programs" },
    { "strategy": "Digital Marketing" },
    { "strategy": "Geographic Diversification" },
    { "strategy": "Process Automation" },
    { "strategy": "Performance Incentives" },
    { "strategy": "R&D Investment" },
    { "strategy": "Quality Improvement" },
    { "strategy": "Unique Value" },
    { "strategy": "Content Marketing" },
    { "strategy": "Budget Planning" },
    { "strategy": "Logistics Optimization" },
    { "strategy": "Green Initiatives" },
    { "strategy": "Contingency Planning" },
    { "strategy": "Talent Acquisition" },
    { "strategy": "Community Engagement" },
    { "strategy": "Policy Adherence" },
    { "strategy": "Pricing Optimization" },
    { "strategy": "Expense Management" },
    { "strategy": "Customer Experience" },
    { "strategy": "Influencer Marketing" },
    { "strategy": "Franchise Model" },
    { "strategy": "Workflow Automation" },
    { "strategy": "Skill Development" },
    { "strategy": "Product Differentiation" },
    { "strategy": "Service Excellence" },
    { "strategy": "Niche Focus" },
    { "strategy": "SEO Strategies" },
    { "strategy": "Cash Flow Control" },
    { "strategy": "Vendor Management" },
    { "strategy": "Renewable Solutions" },
    { "strategy": "Crisis Prevention" },
    { "strategy": "Leadership Development" },
    { "strategy": "Ethical Practices" },
    { "strategy": "Regulatory Adherence" },
    { "strategy": "Persuasive Copywriting" },
    { "strategy": "Cross-Functional Teams" },
    { "strategy": "Brand Storytelling" },
    { "strategy": "Referral Programs" },
    { "strategy": "Strategic Alliances" },
    { "strategy": "User Feedback" },
    { "strategy": "Lean Operations" },
    { "strategy": "Task Prioritization" },
    { "strategy": "Data Analytics" },
    { "strategy": "Workplace Culture" },
    { "strategy": "Rapid Response" }
  ],
  "budgetGoals": [
    { "goal": "₹1,00,000 - ₹2,00,000" },
    { "goal": "₹75,000 - ₹1,00,000" },
    { "goal": "₹1,50,000 - ₹2,50,000" },
    { "goal": "₹1,50,000 - ₹2,00,000" },
    { "goal": "₹1,75,000 - ₹2,80,000" },
    { "goal": "₹2,00,000 - ₹3,00,000" },
    { "goal": "₹2,40,000 - ₹3,60,000" },
    { "goal": "₹75,000 - ₹90,000" },
    { "goal": "₹60,000 - ₹77,500" },
    { "goal": "₹75,000 - ₹1,00,000" },
    { "goal": "₹1,00,000 - ₹1,50,000" },
    { "goal": "₹1,50,000 - ₹2,00,000" },
    { "goal": "₹2,00,000 - ₹2,50,000" },
    { "goal": "₹2,50,000 - ₹3,00,000" },
    { "goal": "₹3,00,000 - ₹3,50,000" },
    { "goal": "₹4,00,000 - ₹4,50,000" },
    { "goal": "₹4,50,000 - ₹5,00,000" },
    { "goal": "₹5,50,000 - ₹6,00,000" },
    { "goal": "₹5,00,000 - ₹5,50,000" },
    { "goal": "₹5,50,000 - ₹6,00,000" },
    { "goal": "₹7,50,000 - ₹8,00,000" },
    { "goal": "₹6,50,000 - ₹7,00,000" },
    { "goal": "₹7,00,000 - ₹8,00,000" },
    { "goal": "₹9,00,000 - ₹9,50,000" },
    { "goal": "₹9,00,000 - ₹10,00,000" }
  ],
  "timeDuration": [
    { "duration": "6 Months" },
    { "duration": "12 Months" },
    { "duration": "18 Months" },
    { "duration": "24 Months" },
    { "duration": "30 Months" },
    { "duration": "36 Months" },
    { "duration": "48 Months" }
  ]
}