export const businessForeCastData = {
    Industry: [
        { "Industry": "D Printing" },
        { "Industry": "Manufacturing" },
        { "Industry": "Prototyping" },
        { "Industry": "Aerospace" },
        { "Industry": "Aviation" },
        { "Industry": "Space" },
        { "Industry": "Agriculture" },
        { "Industry": "Agri-Tech" },
        { "Industry": "Artificial Intelligence" },
        { "Industry": "Robotics" },
        { "Industry": "Automation" },
        { "Industry": "Augmented Reality" },
        { "Industry": "Mixed Reality" },
        { "Industry": "Spatial Computing" },
        { "Industry": "Automotive" },
        { "Industry": "Mobility" },
        { "Industry": "Electric Vehicles" },
        { "Industry": "Autonomous Vehicles" },
        { "Industry": "Self-Driving" },
        { "Industry": "Banking" },
        { "Industry": "Finance" },
        { "Industry": "FinTech" },
        { "Industry": "Beauty" },
        { "Industry": "Skincare" },
        { "Industry": "Personal Care" },
        { "Industry": "Biotechnology" },
        { "Industry": "Genetics" },
        { "Industry": "Life Sciences" },
        { "Industry": "Blockchain" },
        { "Industry": "Cryptocurrency" },
        { "Industry": "Web3" },
        { "Industry": "Consulting" },
        { "Industry": "Construction" },
        { "Industry": "Engineering" },
        { "Industry": "Infrastructure" },
        { "Industry": "Cybersecurity" },
        { "Industry": "Data Privacy" },
        { "Industry": "IT Security" },
        { "Industry": "Drones" },
        { "Industry": "E-commerce" },
        { "Industry": "Retail" },
        { "Industry": "Marketplaces" },
        { "Industry": "EdTech" },
        { "Industry": "Digital Learning" },
        { "Industry": "Education" },
        { "Industry": "Training" },
        { "Industry": "Elderly Care" },
        { "Industry": "Healthcare" },
        { "Industry": "Assisted Living" },
        { "Industry": "Energy" },
        { "Industry": "Utilities" },
        { "Industry": "Power" },
        { "Industry": "Entertainment" },
        { "Industry": "Media" },
        { "Industry": "Broadcasting" },
        { "Industry": "Ethical Business" },
        { "Industry": "Sustainability" },
        { "Industry": "Event Planning" },
        { "Industry": "Weddings" },
        { "Industry": "Fashion" },
        { "Industry": "Apparel" },
        { "Industry": "Textiles" },
        { "Industry": "Fitness" },
        { "Industry": "Wellness" },
        { "Industry": "Food" },
        { "Industry": "Beverage" },
        { "Industry": "Consumer Goods" },
        { "Industry": "Gaming" },
        { "Industry": "Esports" },
        { "Industry": "Healthcare" },
        { "Industry": "Medical" },
        { "Industry": "Pharmaceuticals" },
        { "Industry": "Home Automation" },
        { "Industry": "IoT" },
        { "Industry": "Home Services" },
        { "Industry": "Hospitality" },
        { "Industry": "Tourism" },
        { "Industry": "Human Resources" },
        { "Industry": "Recruitment" },
        { "Industry": "Industrial" },
        { "Industry": "Technology" },
        { "Industry": "IT Services" },
        { "Industry": "Telecommunications" },
        { "Industry": "5G" },
        { "Industry": "Connectivity" },
        { "Industry": "Insurance" },
        { "Industry": "Risk Management" },
        { "Industry": "Legal" },
        { "Industry": "Compliance" },
        { "Industry": "Logistics" },
        { "Industry": "Transportation" },
        { "Industry": "Supply Chain" },
        { "Industry": "Luxury Goods" },
        { "Industry": "Jewelry" },
        { "Industry": "Luxury Travel" },
        { "Industry": "VIP Services" },
        { "Industry": "Metaverse" },
        { "Industry": "Digital Reality" },
        { "Industry": "Pet Care" },
        { "Industry": "Veterinary" },
        { "Industry": "Publishing" },
        { "Industry": "Printing" },
        { "Industry": "Real Estate" },
        { "Industry": "Renewable Energy" },
        { "Industry": "Green Tech" },
        { "Industry": "Smart Homes" },
        { "Industry": "Social Media" },
        { "Industry": "Influencer Marketing" },
        { "Industry": "Space Tourism" },
        { "Industry": "Astrobiology" },
        { "Industry": "Virtual Reality" },
        { "Industry": "Waste Management" },
        { "Industry": "Recycling" },
        { "Industry": "Water Purification" },
        { "Industry": "Finland" }
    ],
    "Revenue Drivers": [
        { name: "Product Sales" },
        { name: "Service Fees" },
        { name: "Subscription Revenue" },
        { name: "Licensing Fees" },
        { name: "Advertising Revenue" },
        { name: "Affiliate Marketing" },
        { name: "Commission-based Revenue" },
        { name: "Transaction Fees" },
        { name: "Sponsorship Deals" },
        { name: "Membership Fees" },
        { name: "Royalties" },
        { name: "Consulting Fees" },
        { name: "Pay-per-Use Revenue" },
        { name: "Rental Income" },
        { name: "Franchising Fees" },
        { name: "Digital Revenue" },
        { name: "Lead Generation Fees" },
        { name: "Crowdfunding" },
        { name: "Donations" },
        { name: "Government Grants" }
    ],
    "Seasons": [
        { name: "Peak Season" },
        { name: "Off-Season" },
        { name: "Shoulder Season" },
        { name: "Holiday Season" },
        { name: "Festive Season" },
        { name: "Back-to-School Season" },
        { name: "Tourist Season" },
        { name: "Summer Season" },
        { name: "Winter Season" },
        { name: "Spring Season" },
        { name: "Autumn (Fall) Season" },
        { name: "Black Friday & Cyber Monday" },
        { name: "Christmas & New Year Season" },
        { name: "Easter Season" },
        { name: "Valentine's Day Season" },
        { name: "Halloween Season" },
        { name: "Tax Season" },
        { name: "Year-end/Year-End" },
        { name: "Sales Discount Season" },
        { name: "Shopping Season" }
    ],
    "Target Audience": [
        { name: "Children (0-12 years)" },
        { name: "Teenagers (13-19 years)" },
        { name: "Young Adults (20-35 years)" },
        { name: "Middle Aged Adults (35-65 years)" },
        { name: "Seniors (65+ years)" },
        { name: "Low Income Consumers" },
        { name: "Middle Class Consumers" },
        { name: "High Income Consumers" },
        { name: "B2B (Business to Business)" },
        { name: "B2C (Business to Consumer)" },
        { name: "SMEs (Small & Medium Enterprises)" },
        { name: "Large Enterprise" },
        { name: "Startups" },
        { name: "Freelancers & Solopreneurs" },
        { name: "Government & Public Sector" },
        { name: "Non-Profit Organizations" },
        { name: "Retail Customers" },
        { name: "Wholesale Buyers" },
        { name: "Tech Enthusiasts" },
        { name: "Students & Educational Institutions" },
        { name: "Healthcare Professionals" },
        { name: "Financial & Banking Sector" },
        { name: "E-commerce Shoppers" },
        { name: "Luxury Consumers" },
        { name: "Millennials" },
        { name: "Gen Z" },
        { name: "Baby Boomers" },
        { name: "High-Net-Worth Individuals (HNWIs)" }
    ],
    "Growth Assumption": [
        { name: "Market Expansion" },
        { name: "Customer Acquisition Rate" },
        { name: "Customer Retention Rate" },
        { name: "Revenue Growth Rate" },
        { name: "Pricing Strategy Impact" },
        { name: "Product Line Expansion" },
        { name: "Geographical Expansion" },
        { name: "Marketing & Advertising ROI" },
        { name: "Operational Efficiency Improvements" },
        { name: "Technology & Automation Adoption" },
        { name: "Competitive Landscape Changes" },
        { name: "Economic Growth Influence" },
        { name: "Resource Availability" },
        { name: "Consumer Spending Behavior" },
        { name: "Regulatory & Compliance Impact" },
        { name: "Seasonality & Demand Fluctuations" },
        { name: "New Market Entry Potential" },
        { name: "Brand-Loyalty & Customer Lifetime Value (CLV)" },
        { name: "Supply Chain Stability" },
        { name: "Investment & Funding Availability" },
        { name: "Partnerships & Strategic Alliances" }
    ],
    "Forecast period": [
        { name: "Weekly" },
        { name: "Bi-Weekly" },
        { name: "Monthly" },
        { name: "Quarterly" },
        { name: "Semi-Annual (Half Yearly)" },
        { name: "Annual (Yearly)" },
        { name: "Biennial (Every 2 Years)" },
        { name: "Triennial (Every 3 Years)" },
        { name: "Five Year Forecast" },
        { name: "Ten Year Forecast" },
        { name: "Short Term (0-6 Months)" },
        { name: "Medium Term (1-3 Years)" },
        { name: "Long-Term (3+ Years)" },
        { name: "Fiscal Year Forecast" }
    ],
    "Revenue goals": [
        { name: "Increase Total Revenue" },
        { name: "Improve Profit Margins" },
        { name: "Grow Recurring Revenue" },
        { name: "Boost Customer lifetime Value (CLV)" },
        { name: "Expand Market Share" },
        { name: "Increase Average Transaction Value" },
        { name: "Enhance Customer Retention Revenue" },
        { name: "Diversify Revenue Streams" },
        { name: "Achieve Break Even Point" },
        { name: "Maximize Upselling & Cross-Selling" },
        { name: "Optimize Pricing Strategy for Higher Revenue" },
        { name: "Expand into New Markets for Revenue Growth" },
        { name: "Improve Sales Conversion Rates" },
        { name: "Increase Revenue per Employee" },
        { name: "Achieve Specific Quarterly/Annual Revenue Targets" },
        { name: "Enhance E-commerce Sales Revenue" },
        { name: "Drive More Revenue from Subscription Models" },
        { name: "Monetize New Products/Services" },
        { name: "Reduce Revenue Leakage" },
        { name: "Achieve Sustainable Year-over-Year Growth" }
    ]
};
