export const eduLoanOptions = {
    "banknames": [
        { "name": "Bank of Baroda" },
        { "name": "Bank of India" },
        { "name": "Bank of Maharashtra" },
        { "name": "Canara Bank" },
        { "name": "Central Bank of India" },
        { "name": "Indian Bank" },
        { "name": "Indian Overseas Bank" },
        { "name": "Punjab and Sind Bank" },
        { "name": "Punjab National Bank" },
        { "name": "State Bank of India" },
        { "name": "UCO Bank" },
        { "name": "Union Bank of India" },
        { "name": "Axis Bank" },
        { "name": "Bandhan Bank" },
        { "name": "CSB Bank" },
        { "name": "City Union Bank" },
        { "name": "DCB Bank" },
        { "name": "Dhanlaxmi Bank" },
        { "name": "Federal Bank" },
        { "name": "HDFC Bank" },
        { "name": "ICICI Bank" },
        { "name": "IDBI Bank" },
        { "name": "IDFC First Bank" },
        { "name": "IndusInd Bank" },
        { "name": "Jammu & Kashmir Bank" },
        { "name": "Karnataka Bank" },
        { "name": "Karur Vysya Bank" },
        { "name": "Kotak Mahindra Bank" },
        { "name": "Nainital Bank" },
        { "name": "RBL Bank" },
        { "name": "South Indian Bank" },
        { "name": "Tamilnad Mercantile Bank" },
        { "name": "Yes Bank" },
        { "name": "Andhra Pradesh Grameena Vikas Bank" },
        { "name": "Andhra Pragathi Grameena Bank" },
        { "name": "Chaitanya Godavari Grameena Bank" },
        { "name": "Saptagiri Grameena Bank" },
        { "name": "Arunachal Pradesh Rural Bank" },
        { "name": "Assam Gramin Vikash Bank" },
        { "name": "Dakshin Bihar Gramin Bank" },
        { "name": "Uttar Bihar Gramin Bank" },
        { "name": "Chhattisgarh Rajya Gramin Bank" },
        { "name": "Baroda Gujarat Gramin Bank" },
        { "name": "Saurashtra Gramin Bank" },
        { "name": "Sarva Haryana Gramin Bank" },
        { "name": "Himachal Pradesh Gramin Bank" },
        { "name": "Ellaquai Dehati Bank" },
        { "name": "Jammu And Kashmir Grameen Bank" },
        { "name": "Jharkhand Rajya Gramin Bank" },
        { "name": "Karnataka Gramin Bank" },
        { "name": "Karnataka Vikas Grameena Bank" },
        { "name": "Kerala Gramin Bank" },
        { "name": "Madhya Pradesh Gramin Bank" },
        { "name": "Madhyanchal Gramin Bank" },
        { "name": "Maharashtra Gramin Bank" },
        { "name": "Vidarbha Konkan Gramin Bank" },
        { "name": "Manipur Rural Bank" },
        { "name": "Meghalaya Rural Bank" },
        { "name": "Mizoram Rural Bank" },
        { "name": "Nagaland Rural Bank" },
        { "name": "Odisha Gramya Bank" },
        { "name": "Utkal Grameen Bank" },
        { "name": "Puduvai Bharathiar Grama Bank" },
        { "name": "Punjab Gramin Bank" },
        { "name": "Rajasthan Marudhara Gramin Bank" },
        { "name": "Baroda Rajasthan Kshetriya Gramin Bank" },
        { "name": "Tamil Nadu Grama Bank" },
        { "name": "Telangana Grameena Bank" },
        { "name": "Tripura Gramin Bank" },
        { "name": "Aryavart Bank" },
        { "name": "Baroda UP Bank" },
        { "name": "Prathama UP Gramin Bank" },
        { "name": "Uttarakhand Gramin Bank" },
        { "name": "Bangiya Gramin Vikash Bank" },
        { "name": "Paschim Banga Gramin Bank" },
        { "name": "Uttarbanga Kshetriya Gramin Bank" },
        { "name": "Ahmedabad Mercantile Co-Op Bank Ltd." },
        { "name": "Kalupur Commercial Coop.Bank Ltd." },
        { "name": "Mehsana Urban Co-Op Bank Ltd." },
        { "name": "Nutan Nagarik Sahakari Bank Ltd., Ahmedabad" },
        { "name": "Rajkot Nagrik Sahakari Bank Ltd." },
        { "name": "SBPP Co-operative Bank Ltd., Killa Pardi, Dist Valsad (Gujarat)" },
        { "name": "Surat Peoples Coop Bank Ltd." },
        { "name": "Amanath Co-operative Bank Ltd." },
        { "name": "Andhra Pradesh Mahesh Co-Op Urban Bank Ltd." },
        { "name": "Indian Mercantile Co-operative Bank Ltd." },
        { "name": "Abhyudaya Co-operative Bank Ltd., Mumbai" },
        { "name": "Apna Sahakari Bank Ltd." },
        { "name": "Bassein Catholic Co-operative Bank Ltd." },
        { "name": "Bharat Co-operative Bank (Mumbai) Ltd., Mumbai" },
        { "name": "Bharati Sahakari Bank Limited." },
        { "name": "Bombay Mercantile Co-operative Bank Limited" },
        { "name": "Citizen Credit Co-operative Bank Ltd., Mumbai" },
        { "name": "Cosmos Co-operative Bank Ltd" },
        { "name": "Dombivli Nagari Sahakari Bank Ltd." },
        { "name": "G. P. Parsik Janata Sahakari Bank Ltd., Thane" },
        { "name": "Greater Bombay Co-operative Bank Limited" },
        { "name": "GS Mahanagar Co-operative Bank Ltd., Mumbai" },
        { "name": "Jalgaon Janata Sahakari Bank Ltd." },
        { "name": "Jalgaon People's Co-operative Bank Ltd." },
        { "name": "Janakalyan Sahakari Bank Ltd., Mumbai" },
        { "name": "Janalaxmi Co-operative Bank Ltd., Nashik" },
        { "name": "Janata Sahakari Bank Ltd., Pune." },
        { "name": "Kallappanna Awade Ichalkaranji Janata Sahakari Bank Ltd." },
        { "name": "Kalyan Janata Sahakari Bank Ltd., Kalyan" },
        { "name": "Karad Urban Co-operative Bank Ltd." },
        { "name": "Nasik Merchant's Co-operative Bank Ltd." },
        { "name": "New India Co-operative Bank Ltd., Mumbai" },
        { "name": "NKGSB Co-operative Bank Ltd., Mumbai" },
        { "name": "Pravara Sahakari Bank Ltd." },
        { "name": "Rajarambapu Sahakari Bank Ltd." },
        { "name": "Sangli Urban Co-operative Bank Ltd., Sangli" },
        { "name": "Saraswat Co-operative Bank Ltd., Bombay" },
        { "name": "Shamrao Vithal Co-operative Bank Ltd." },
        { "name": "Solapur Janata Sahakari Bank Ltd." },
        { "name": "Thane Bharat Sahakari Bank Ltd." },
        { "name": "TJSB Sahakari Bank" },
        { "name": "Vasai Vikas Sahakari Bank Ltd." },
        { "name": "Zoroastrian Co-operative Bank Ltd., Bombay" },
        { "name": "Nagpur Nagrik Sahakari Bank Ltd." },
        { "name": "Shikshak Sahakari Bank Ltd., Nagpur" },
        { "name": "The Akola Janata Commercial Co-operative Bank Ltd., Akola" },
        { "name": "The Akola Urban Co-operative Bank Ltd., Akola" },
        { "name": "The Khamgaon Urban Co-operative Bank Ltd., Khamgaon" },
        { "name": "Goa Urban Co-operative Bank Limited." },
        { "name": "Akhand Anand Co-Operative Bank Ltd., Surat" },
        { "name": "Alavi Co-Op Bank Ltd." },
        { "name": "Amarnath Co-operative" },
        { "name": "Bank Ltd., Ahmedabad" },
        { "name": "Amod Nagric Co-op. Bank Ltd." },
        { "name": "Amreli Nagrik Sahakari Bank Ltd." },
        { "name": "Anand Mercantile Co-Op Bank Ltd." },
        { "name": "Apani Sahakari Bank Ltd., Ahmedabad." },
        { "name": "Balsinor Nagarik Sahakari Bank Ltd." },
        { "name": "Banaskantha Mercantile co-op Bank Limited." },
        { "name": "Bapunagar Mahila Co-operative Bank Ltd." },
        { "name": "Bardoli Nagrik Sahakari Bank Ltd." },
        { "name": "Baroda City Co-op. Bank Limited." },
        { "name": "Bavla Nagarik Sahakari Bank Limited." },
        { "name": "Bechraji Nagarik Sahakari Bank Ltd." },
        { "name": "Bhabhar Vibhag Nagarik sahakari Bank Limited." },
        { "name": "Bhadran People's Co op Bank Ltd." },
        { "name": "Bhagyodaya Co-op Bank Limited." },
        { "name": "Bhuj Commercial Co op Bank Ltd." },
        { "name": "Bhuj Mercantile Co-operative Bank Ltd., Bhuj" },
        { "name": "Bodeli Urban Co op Bank Ltd." },
        { "name": "Chanasma Commercial Coop. Bank Ltd." },
        { "name": "Chanasma Nagrik Sahakari Bank Ltd." },
        { "name": "Charda Nagrik Sahakari Bank Ltd., Charada" },
        { "name": "Chhapi Nagrik Sahakari Bank Ltd." },
        { "name": "Citizen Coop Bank Limited Rajkot." },
        { "name": "Colour Merchants'Coop Bank Ltd., Ahmedabad." },
        { "name": "Commercial Co-Operative Bank Ltd.," },
        { "name": "Commercial Cooperative Bank Ltd.Jamnagar" },
        { "name": "Coop.Bank Of Rajkot Ltd." },
        { "name": "Co-operative bank of Mehsana Ltd., Mehsana" },
        { "name": "Dahod Mercantile Co-op. Bank Ltd." },
        { "name": "Dahod Urban Co-op. Bank Ltd." },
        { "name": "Dhanera Mercantile Co-Operative Bank Ltd.," },
        { "name": "Dharmaj Peoples' Co-op.Bank Ltd." },
        { "name": "Dhinoj Nagrik Sahakari Bank Ltd." },
        { "name": "Dhrangadhra Peoples'Co-op. Bank Ltd." },
        { "name": "Financial Co-Operative Bank Ltd.," },
        { "name": "Gandevi People's Co op Bank Limited." },
        { "name": "Gandhidham Co op Bank Limited." },
        { "name": "Gandhidham Mercantile Co-op.Bk.Ltd., Gandhidham" },
        { "name": "Gandhinagar Nagarik Co op Bank Limited." },
        { "name": "Gandhinagar Urban Co-operative Bank Ltd., Gandhinagar" },
        { "name": "Ghoghamba Vibhag Nagarik Sahakari Bank Limited." },
        { "name": "Godhra City Co op Bank Limited." },
        { "name": "Godhra Urban Co op Bank Limited." },
        { "name": "Gondal Nagarik Sahakari Bank Limited." },
        { "name": "Gozaria Nagrik Sahakari Bank Ltd." },
        { "name": "Gujarat Ambuja Co-operative Bank Ltd., Ahmedabad" },
        { "name": "Gujarat Mercantile Co-Operative Bank Ltd." },
        { "name": "Halol Mercantile Coop Bank Limited." },
        { "name": "Halol Urban Coop Bank Limited." },
        { "name": "Hansot Nagrik Sahakari Bank Limited." },
        { "name": "Harij Nagrik Sahakari Bank Ltd." },
        { "name": "Himatnagar Nagrik Sahakari Bank Limited." },
        { "name": "Idar Nagrik Sahakari Bank Ltd." },
        { "name": "Jamnagar mahila Sahakari Bank Ltd" },
        { "name": "Jamnagar People's Coop Bank Ltd." },
        { "name": "Janata Coop. Bank Ltd Godhra." },
        { "name": "Jhalod Urban Coop Bank Ltd." },
        { "name": "Jivan Commercial Coop Bank Ltd." },
        { "name": "Junagadh Commercial Coop Bank Ltd." },
        { "name": "Kalol Nagarik Sahakari Bank Ltd." },
        { "name": "Kalol Urban Co-op. Bank Ltd." },
        { "name": "Kalyan Cooperative Bank Ltd., Kalol" },
        { "name": "Kankaria Maninagar Nagarik Sahakari Bank Ltd." },
        { "name": "Kapadwanj Peoples' Co-op. Bank Ltd." },
        { "name": "Karjan Nagarik Sahakari Bank Ltd." },
        { "name": "Karnavathi Co-operative Bank Ltd.," },
        { "name": "Khambhat Nagrik Sahakari Bank Ltd." },
        { "name": "Kheda Peoples' Co-op. Bank Ltd." },
        { "name": "Kheralu Nagarik Sahakari Bank Ltd." },
        { "name": "Kodinar Nagarik Sahakari Bank Ltd." },
        { "name": "Kosamba Mercantile Co-op. Bank Ltd." },
        { "name": "Kukarwada Nagrik Sahakari Bank Ltd." },
        { "name": "Lakhvad Nagrik Sahakari Bank Limited." },
        { "name": "Lalbaug Co-Operative Bank Ltd., Baroda" },
        { "name": "Limbasi Urban Coop Bank Limited." },
        { "name": "Limdi Urban Coop Bank Limited." },
        { "name": "Lunawada Nagrik Sahakari Bank Limited." },
        { "name": "Lunawada People's Coop Bank Ltd." },
        { "name": "M.S. Co-Operative Bank Ltd., Vadodara" },
        { "name": "Mahila Co-Operative Nagrik Bank Ltd., Bharuch" },
        { "name": "Mahila Sahakari Bank Ltd., Baroda" },
        { "name": "Mahudha Nagrik Sahakari Bank Ltd." },
        { "name": "Makarpura Industrial Estate Co-op Bank Ltd." },
        { "name": "Malpur Nagrik Sahakari Bank Ltd." },
        { "name": "Mandal Nagarik Sahakari Bank Ltd." },
        { "name": "Mandvi Mercantile Co-operative Bank Ltd." },
        { "name": "Mandvi Nagrik Sahakari Bank LTd." },
        { "name": "Maninagar Co-Op Bank Ltd." },
        { "name": "Mansa Nagrik Sahakari Bank Ltd." },
        { "name": "Marketyard Commercial Cooperative Bank Ltd. Unjha" },
        { "name": "Megharaj Nagrik Sahakari Bank Ltd." },
        { "name": "Mehmadabad Urban People's Co-Op Bank Ltd." },
        { "name": "Mehsana Jilla Panchayat Karmachari Co op BankLtd.Gujarat" },
        { "name": "Mehsana Nagrik Sahakari Bank Ltd." },
        { "name": "Modasa Nagrik Sahakari Bank Ltd." },
        { "name": "Nadiad People's Coop. Bank Ltd." },
        { "name": "Nagarik Sahakari Bank Ltd. Babra" },
        { "name": "Naroda Nagrik Coop.Bank Ltd." },
        { "name": "Navnirman Coop.Bank Ltd." },
        { "name": "Navsarjan Industrial Co-Operative Bank Ltd.," },
        { "name": "Nawanagar Coop. Bank Ltd." },
        { "name": "Nidhi Co-Operative Bank Ltd., Ahmedabad," },
        { "name": "Ode Urban Coop Bank Ltd." },
        { "name": "Padra Nagar Nagrik Sahakari Bank Ltd." },
        { "name": "Panchsheel Mercantile Coop. Bank Ltd." },
        { "name": "Patan Nagarik Sahakari Bank Ltd." },
        { "name": "Patdi Nagrik Sahakari Bank Ltd." },
        { "name": "People's Coop. Bank Ltd.Mochiol Dholka." },
        { "name": "Pij People's Co-Op Bank Ltd." },
        { "name": "Porbandar Commercial Co-Op Bank Ltd." },
        { "name": "Porbandar Vibhagiya Nagarik Sahakari" }
    ],
    "Interest Rate Type": [
        "Fixed Interest Rate",
        "Floating Interest Rate"
    ],
    "Interest Rate": [
        "4%-5%",
        "5%-6%",
        "6%-7%",
        "7%-8%",
        "8%-9%",
        "9%-10%",
        "10%-11%",
        "11%-12%",
        "12%-13%",
        "13%-14%",
        "14%-15%"
    ],
    "Study Duration in months": [
        "6",
        "12",
        "18",
        "24",
        "30",
        "36",
        "42",
        "48"
    ],
    "Moratorium Period: Repayment Start": [
        "Course Duration + 6 Months",
        "Course Duration + 1 year",
        "Course Duration",
        "No moratourium"
    ],
    "Repayment Start": [
        "1 year after course completion",
        "6 months after course completion",
        "Immediate EMI",
        "After course completion"
    ],
    "Repayment Duration in Years": [
        "11",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12"
    ]

}
