export const eduLoanOptions = {
    "bankNames": [
        "Bank of Baroda",
        "Bank of India",
        "Bank of Maharashtra",
        "Canara Bank",
        "Central Bank of India",
        "Indian Bank",
        "Indian Overseas Bank",
        "Punjab and Sind Bank",
        "Punjab National Bank",
        "State Bank of India",
        "UCO Bank",
        "Union Bank of India",
        "Axis Bank",
        "Bandhan Bank",
        "CSB Bank",
        "City Union Bank",
        "DCB Bank",
        "Dhanlaxmi Bank",
        "Federal Bank",
        "HDFC Bank",
        "ICICI Bank",
        "IDBI Bank",
        "IDFC First Bank",
        "IndusInd Bank",
        "Jammu & Kashmir Bank",
        "Karnataka Bank",
        "Karur Vysya Bank",
        "Kotak Mahindra Bank",
        "Nainital Bank",
        "RBL Bank",
        "South Indian Bank",
        "Tamilnad Mercantile Bank",
        "Yes Bank",
        "Andhra Pradesh Grameena Vikas Bank",
        "Andhra Pragathi Grameena Bank",
        "Chaitanya Godavari Grameena Bank",
        "Saptagiri Grameena Bank",
        "Arunachal Pradesh Rural Bank",
        "Assam Gramin Vikash Bank",
        "Dakshin Bihar Gramin Bank",
        "Uttar Bihar Gramin Bank",
        "Chhattisgarh Rajya Gramin Bank",
        "Baroda Gujarat Gramin Bank",
        "Saurashtra Gramin Bank",
        "Sarva Haryana Gramin Bank",
        "Himachal Pradesh Gramin Bank",
        "Ellaquai Dehati Bank",
        "Jammu And Kashmir Grameen Bank",
        "Jharkhand Rajya Gramin Bank",
        "Karnataka Gramin Bank",
        "Karnataka Vikas Grameena Bank",
        "Kerala Gramin Bank",
        "Madhya Pradesh Gramin Bank",
        "Madhyanchal Gramin Bank",
        "Maharashtra Gramin Bank",
        "Vidarbha Konkan Gramin Bank",
        "Manipur Rural Bank",
        "Meghalaya Rural Bank",
        "Mizoram Rural Bank",
        "Nagaland Rural Bank",
        "Odisha Gramya Bank",
        "Utkal Grameen Bank",
        "Puduvai Bharathiar Grama Bank",
        "Punjab Gramin Bank",
        "Rajasthan Marudhara Gramin Bank",
        "Baroda Rajasthan Kshetriya Gramin Bank",
        "Tamil Nadu Grama Bank",
        "Telangana Grameena Bank",
        "Tripura Gramin Bank",
        "Aryavart Bank",
        "Baroda UP Bank",
        "Prathama UP Gramin Bank",
        "Uttarakhand Gramin Bank",
        "Bangiya Gramin Vikash Bank",
        "Paschim Banga Gramin Bank",
        "Uttarbanga Kshetriya Gramin Bank",
        "Ahmedabad Mercantile Co-Op Bank Ltd.",
        "Kalupur Commercial Coop.Bank Ltd.",
        "Mehsana Urban Co-Op Bank Ltd.",
        "Nutan Nagarik Sahakari Bank Ltd., Ahmedabad",
        "Rajkot Nagrik Sahakari Bank Ltd.",
        "SBPP Co-operative Bank Ltd., Killa Pardi, Dist Valsad (Gujarat)",
        "Surat Peoples Coop Bank Ltd.",
        "Amanath Co-operative Bank Ltd.",
        "Andhra Pradesh Mahesh Co-Op Urban Bank Ltd.",
        "Indian Mercantile Co-operative Bank Ltd.",
        "Abhyudaya Co-operative Bank Ltd., Mumbai",
        "Apna Sahakari Bank Ltd.",
        "Bassein Catholic Co-operative Bank Ltd.",
        "Bharat Co-operative Bank (Mumbai) Ltd., Mumbai",
        "Bharati Sahakari Bank Limited.",
        "Bombay Mercantile Co-operative Bank Limited",
        "Citizen Credit Co-operative Bank Ltd., Mumbai",
        "Cosmos Co-operative Bank Ltd",
        "Dombivli Nagari Sahakari Bank Ltd.",
        "G. P. Parsik Janata Sahakari Bank Ltd., Thane",
        "Greater Bombay Co-operative Bank Limited",
        "GS Mahanagar Co-operative Bank Ltd., Mumbai",
        "Jalgaon Janata Sahakari Bank Ltd.",
        "Jalgaon People's Co-operative Bank Ltd.",
        "Janakalyan Sahakari Bank Ltd., Mumbai",
        "Janalaxmi Co-operative Bank Ltd., Nashik",
        "Janata Sahakari Bank Ltd., Pune.",
        "Kallappanna Awade Ichalkaranji Janata Sahakari Bank Ltd.",
        "Kalyan Janata Sahakari Bank Ltd., Kalyan",
        "Karad Urban Co-operative Bank Ltd.",
        "Nasik Merchant's Co-operative Bank Ltd.",
        "New India Co-operative Bank Ltd., Mumbai",
        "NKGSB Co-operative Bank Ltd., Mumbai",
        "Pravara Sahakari Bank Ltd.",
        "Rajarambapu Sahakari Bank Ltd.",
        "Sangli Urban Co-operative Bank Ltd., Sangli",
        "Saraswat Co-operative Bank Ltd., Bombay",
        "Shamrao Vithal Co-operative Bank Ltd.",
        "Solapur Janata Sahakari Bank Ltd.",
        "Thane Bharat Sahakari Bank Ltd.",
        "TJSB Sahakari Bank",
        "Vasai Vikas Sahakari Bank Ltd.",
        "Zoroastrian Co-operative Bank Ltd., Bombay",
        "Nagpur Nagrik Sahakari Bank Ltd.",
        "Shikshak Sahakari Bank Ltd., Nagpur",
        "The Akola Janata Commercial Co-operative Bank Ltd., Akola",
        "The Akola Urban Co-operative Bank Ltd., Akola",
        "The Khamgaon Urban Co-operative Bank Ltd., Khamgaon",
        "Goa Urban Co-operative Bank Limited.",
        "Akhand Anand Co-Operative Bank Ltd., Surat",
        "Alavi Co-Op Bank Ltd.",
        "Amarnath Co-operative Bank Ltd., Ahmedabad",
        "Amod Nagric Co-op. Bank Ltd.",
        "Amreli Nagrik Sahakari Bank Ltd.",
        "Anand Mercantile Co-Op Bank Ltd.",
        "Apani Sahakari Bank Ltd., Ahmedabad.",
        "Balsinor Nagarik Sahakari Bank Ltd.",
        "Banaskantha Mercantile co-op Bank Limited.",
        "Bapunagar Mahila Co-operative Bank Ltd.",
        "Bardoli Nagrik Sahakari Bank Ltd.",
        "Baroda City Co-op. Bank Limited.",
        "Bavla Nagarik Sahakari Bank Limited.",
        "Bechraji Nagarik Sahakari Bank Ltd.",
        "Bhabhar Vibhag Nagarik sahakari Bank Limited.",
        "Bhadran People's Co op Bank Ltd.",
        "Bhagyodaya Co-op Bank Limited.",
        "Bhuj Commercial Co op Bank Ltd.",
        "Bhuj Mercantile Co-operative Bank Ltd., Bhuj",
        "Bodeli Urban Co op Bank Ltd.",
        "Chanasma Commercial Coop. Bank Ltd.",
        "Chanasma Nagrik Sahakari Bank Ltd.",
        "Charda Nagrik Sahakari Bank Ltd., Charada",
        "Chhapi Nagrik Sahakari Bank Ltd.",
        "Citizen Coop Bank Limited Rajkot.",
        "Colour Merchants'Coop Bank Ltd., Ahmedabad.",
        "Commercial Co-Operative Bank Ltd.,",
        "Commercial Cooperative Bank Ltd.Jamnagar",
        "Coop.Bank Of Rajkot Ltd.",
        "Co-operative bank of Mehsana Ltd., Mehsana",
        "Dahod Mercantile Co-op. Bank Ltd.",
        "Dahod Urban Co-op. Bank Ltd.",
        "Dhanera Mercantile Co-Operative Bank Ltd.,",
        "Dharmaj Peoples' Co-op.Bank Ltd.",
        "Dhinoj Nagrik Sahakari Bank Ltd.",
        "Dhrangadhra Peoples'Co-op. Bank Ltd.",
        "Financial Co-Operative Bank Ltd.,",
        "Gandevi People's Co op Bank Limited.",
        "Gandhidham Co op Bank Limited.",
        "Gandhidham Mercantile Co-op.Bk.Ltd., Gandhidham",
        "Gandhinagar Nagarik Co op Bank Limited.",
        "Gandhinagar Urban Co-operative Bank Ltd., Gandhinagar",
        "Ghoghamba Vibhag Nagarik Sahakari Bank Limited.",
        "Godhra City Co op Bank Limited.",
        "Godhra Urban Co op Bank Limited.",
        "Gondal Nagarik Sahakari Bank Limited.",
        "Gozaria Nagrik Sahakari Bank Ltd.",
        "Gujarat Ambuja Co-operative Bank Ltd., Ahmedabad",
        "Gujarat Mercantile Co-Operative Bank Ltd.",
        "Halol Mercantile Coop Bank Limited.",
        "Halol Urban Coop Bank Limited.",
        "Hansot Nagrik Sahakari Bank Limited.",
        "Harij Nagrik Sahakari Bank Ltd.",
        "Himatnagar Nagrik Sahakari Bank Limited.",
        "Idar Nagrik Sahakari Bank Ltd.",
        "Jamnagar mahila Sahakari Bank Ltd",
        "Jamnagar People's Coop Bank Ltd.",
        "Janata Coop. Bank Ltd Godhra.",
        "Jhalod Urban Coop Bank Ltd.",
        "Jivan Commercial Coop Bank Ltd.",
        "Junagadh Commercial Coop Bank Ltd.",
        "Kalol Nagarik Sahakari Bank Ltd.",
        "Kalol Urban Co-op. Bank Ltd.",
        "Kalyan Cooperative Bank Ltd., Kalol",
        "Kankaria Maninagar Nagarik Sahakari Bank Ltd.",
        "Kapadwanj Peoples' Co-op. Bank Ltd.",
        "Karjan Nagarik",
        "Nagarik Sahakari Bank Ltd.",
        "Karnavathi Co-operative Bank Ltd.,",
        "Khambhat Nagrik Sahakari Bank Ltd.",
        "Kheda Peoples' Co-op. Bank Ltd.",
        "Kheralu Nagarik Sahakari Bank Ltd.",
        "Kodinar Nagarik Sahakari Bank Ltd.",
        "Kosamba Mercantile Co-op. Bank Ltd.",
        "Kukarwada Nagrik Sahakari Bank Ltd.",
        "Lakhvad Nagrik Sahakari Bank Limited.",
        "Lalbaug Co-Operative Bank Ltd., Baroda",
        "Limbasi Urban Coop Bank Limited.",
        "Limdi Urban Coop Bank Limited.",
        "Lunawada Nagrik Sahakari Bank Limited.",
        "Lunawada People's Coop Bank Ltd.",
        "M.S. Co-Operative Bank Ltd., Vadodara",
        "Mahila Co-Operative Nagrik Bank Ltd., Bharuch",
        "Mahila Sahakari Bank Ltd., Baroda",
        "Mahudha Nagrik Sahakari Bank Ltd.",
        "Makarpura Industrial Estate Co-op Bank Ltd.",
        "Malpur Nagrik Sahakari Bank Ltd.",
        "Mandal Nagarik Sahakari Bank Ltd.",
        "Mandvi Mercantile Co-operative Bank Ltd.",
        "Mandvi Nagrik Sahakari Bank LTd.",
        "Maninagar Co-Op Bank Ltd.",
        "Mansa Nagrik Sahakari Bank Ltd.",
        "Marketyard Commercial Cooperative Bank Ltd. Unjha",
        "Megharaj Nagrik Sahakari Bank Ltd.",
        "Mehmadabad Urban People's Co-Op Bank Ltd.",
        "Mehsana Jilla Panchayat Karmachari Co op BankLtd.Gujarat",
        "Mehsana Nagrik Sahakari Bank Ltd.",
        "Modasa Nagrik Sahakari Bank Ltd.",
        "Nadiad People's Coop. Bank Ltd.",
        "Nagarik Sahakari Bank Ltd. Babra",
        "Naroda Nagrik Coop.Bank Ltd.",
        "Navnirman Coop.Bank Ltd.",
        "Navsarjan Industrial Co-Operative Bank Ltd.,",
        "Nawanagar Coop. Bank Ltd.",
        "Nidhi Co-Operative Bank Ltd., Ahmedabad,",
        "Ode Urban Coop Bank Ltd.",
        "Padra Nagar Nagrik Sahakari Bank Ltd.",
        "Panchsheel Mercantile Coop. Bank Ltd.",
        "Patan Nagarik Sahakari Bank Ltd.",
        "Patdi Nagrik Sahakari Bank Ltd.",
        "People's Coop. Bank Ltd.Mochiol Dholka.",
        "Pij People's Co-Op Bank Ltd.",
        "Porbandar Commercial Co-Op Bank Ltd.",
        "Porbandar Vibhagiya Nagarik Sahakari Bank Ltd.",
        "Pragati Coop Bank Ltd., Thara.",
        "Pragati Sahakari Bank Ltd., Baroda",
        "Prime Co-operative Bank Ltd., Surat",
        "Progressive Mercantile Coop Bank Ltd., Ahmedabad",
        "Rajkot Commercial Cooperative Bank Ltd.",
        "Rajkot Peoples Co-Operative Bank Ltd.,",
        "Rajpipla Nagrik Sahakari Bank Ltd.",
        "Rajula Nagrik Sahakari Bank Ltd.",
        "Rander People's Co-Op Bank Ltd.",
        "Randheja Commercial Co-Op Bank Ltd.",
        "Ranuj Nagrik Sahakari Bank Ltd.",
        "Sankheda Nagarik Sahakari Bank Ltd.",
        "Santrampur Urban Co op Bank Ltd.",
        "Sarangpur Co op Bank Limited.",
        "Saraspur Nagarik Co op Bank Limited.",
        "Sardar Vallabhbhai Sahakari Bank Limited.",
        "Sardarganj Mercantile Coop Bank Ltd., Anand",
        "Sardargunj Mercantile Coop Bank Ltd., Patan",
        "Sarsa People's Co op Bank Limited.",
        "Sarvodaya Commercial Coop Bank Ltd., Mehsana",
        "Sarvodaya Nagrik Sahakari Bank Ltd., Himmatnagar",
        "Sarvodaya Sahakari Bank Ltd., Modasa",
        "Sarvodaya Sahakari Bank Ltd., Surat",
        "Sathamba People's Co op Bank Ltd.",
        "Saurashtra Co op Bank Ltd.",
        "Sevalia Urban Co op Bank Ltd.",
        "Shihori Nagarik Sahakari Bank ltd., Shihori",
        "Shree Virpur Urban Sahakari Bank Ltd.",
        "Shree Baria Nagarik Sahakari Bank Ltd.",
        "Shree Bharat Coop Bank Ltd., Baroda.",
        "Shree Bhavnagar Nagrik Sahakari Bank Limited.",
        "Shree Botad Mercantile Co op Bank Ltd.",
        "Shree Coop. Bank Ltd.Baroda.",
        "Shree Dhandhuka Janta Sahakari Bank Ltd.",
        "Shree Dharati Cooperative Bank Ltd., Rajkot",
        "Shree Kadi Nagrik Sahakari Bank Ltd.",
        "Shree Laxmi Mahila Sahakari Bank Ltd, Mehsana",
        "Shree Lodhra Nagrik Sahakari Bank Ltd.",
        "Shree Mahuva Nagrik Sahakari Bank Ltd.",
        "Shree Parswanth Co-Operative Bank Ltd., Rajkot",
        "Shree Savarkundla Nagrik Sahakari Bank Ltd.",
        "Shree Savli Nagrik Sahakari Bank Ltd.",
        "Shree Talaja Nagarik Sahakari Bank Limited.",
        "Shree Vardhaman Sahakari Bank Ltd., Vadodra",
        "Shri Bagasara Nagrik Sahakari Bank Limited.",
        "Shri Bhailalbhai Contractor Smarak Co-operative Bank Ltd., Vadodara",
        "Shri Bhavnagar Mahila Nagarik Sahakari Bank Ltd.",
        "Shri Chhani Nagrik Sahakari Bank Limited.",
        "Shri Janata Sahakari Bank Ltd., Halol",
        "Shri Mahila Sewa Sahakari Bank Ltd., Ahmedabad",
        "Shri Morbi Nagrik Sahakari Bank Ltd.",
        "Shri Vinayak Sahakari Bank Limited. Ahmedabad",
        "Sihor Mercantile Co op Bank Ltd.",
        "Sihor Nagrik Sahakari Bank Ltd.",
        "Sinor Nagrik Sahakari Bank Ltd.",
        "Suleimani Coop.Bank Ltd., Baroda",
        "Surat Mercantile Coop Bank Ltd.",
        "Surat National Coop Bank Ltd.",
        "Talod Nagarik Sahakari Bank Ltd.",
        "Tarapur Co-Op Urban Bank Ltd.",
        "Textile Traders'Coop Bank Ltd., Ahmedabad",
        "Thasra Peoples'Co-Op Bank Ltd.",
        "The Adinath Co-operative Bank Ltd., Surat.",
        "The Associate Co-operative Bank Ltd., Surat.",
        "The Gujarat Rajya Karmachari Cooperative Bank Ltd., Ahmedabad",
        "The Jambusar People's Coop Bank Ltd.",
        "The Kutch Mercantile Co-operative Bank Ltd., Kutch",
        "The Social Coop Bank Ltd., Ahmedabad",
        "The Sutex Co operative Bank Ltd.",
        "Uma Cooperative Bank Ltd., Baroda",
        "Umreth Urban Co op Bank Ltd.",
        "Una Peoples' Co-op. Bank Ltd.",
        "Unava Nagrik Sahakari Bank Ltd.",
        "Union Co op Bank Limited Naroda.",
        "United Coop Bank Ltd., Ahmedabad",
        "Unjha Nagarik Sahakari Bank Ltd.",
        "Uttarsanda Peoples Coop Bank Ltd;",
        "Vadali Nagrik Sahakari Bank Ltd.",
        "Vadnagar Nagrik Sahakari Bank Limited.",
        "Vallabh Vidhyanagar Commercial Co op Bank Ltd.",
        "Valsad Mahila Nagrik Sahakari Bank Ltd.",
        "Varachha Co-operative bank Ltd., Surat",
        "Vejalpur Nagarik Sahakari bank Ltd.",
        "Vepar Udhyog Vikas Sahakari Bank Limited.",
        "Veraval Mercantile Coop Bank Limited.",
        "Veraval Peoples Coop Bank Limited.",
        "Vijapur Nagrik Sahakari Bank Limited.",
        "Vijay Commercial Coop Bank Limited.",
        "Vijay Coop Bank Limited.",
        "Viramgam Mercantile Coop Bank Limited.",
        "Waghodia Urban Coop Bank Ltd.",
        "Abhivriddhi Mahila Sahakara Bank Niyamita, Gulbarga",
        "Abhyudaya Mahila Urban Co-operative Bank Ltd., Channapatna",
        "Accountant General's Office Employees Co-operative Bank Ltd.Bangalore",
        "Adarsha Pattana Souharda Sahakara Bank Niyamitha., Harapanahalli",
        "Akki-Alur Urban Co-operative Bank Ltd. Akki-Alur",
        "Almel Urban Co-operative Bank Ltd., Almel",
        "Alnavar Urban Co-operative Bank Ltd. Alnavar",
        "Ananda Co-operative Bank Ltd., Bangalore.",
        "Ankola Urban Co-operative Bank Ltd., Ankola",
        "Aroodhjyoti Pattan Sahakara Bank Niyamith, Athani",
        "Arsikere Urban Co-operative Bank Ltd., Arsikere",
        "Aruna Sahakara Bank Niyamitha, Bangalore",
        "Arya Vaishya Co-operative Bank Ltd., Hubli",
        "Ashoknagar Co-operative Bank Ltd., Bangalore",
        "Azad Co-operative Bank Ltd., Gadag",
        "Azad Co-operative Bank Ltd., Hubli",
        "Bagalkot Urban Co-operative Bank Ltd., Bagalkot",
        "Basoda Nagrik Sahakari Bank Maryadit., Ganj Basoda",
        "Betul Nagarik Sahakari Bank Maryadit.",
        "Bhind Nagarik Sahakari Bank Maryadit.",
        "Dr.Ambedkar Nagarik Sah.Bk.Maryadit, Gwalior",
        "Guna Nagarik sahakari Bank Maryadit, Guna",
        "Indore Cloth Market Coop. Bank Ltd..",
        "Indore Paraspar Sahakari Bank Maryadit.",
        "Indore Swayamsidha Mahila Co-Operative Bank Maryadit,",
        "Jabalpur Mahila Nagarik Sahakari Bank Maryadit.",
        "Jharneswar Nagarik Sah Bank Maryadit, Bhopal",
        "Khargon Nagrik Sahakari Bank Maryadit.",
        "Krishna Mercantile Co-Operative Bank Maryadit,",
        "Lakshmibai Mahila Nagarik Sahakari Bank Maryadit.",
        "Maa Sharda Mahila Nagrik Sahakari Bank Maryadit",
        "Mahanagar Nagrik Sahakari Bank Maryadit, Bairagarh",
        "Mahismati Nagrik Sahakari Bank Maryadit., Mandla",
        "Nagarik Sahakari Bank Maryadit, Gwalior.",
        "Nagarik Sahakari Bank maryadit., Rajgarh",
        "Nagarik Sahakari Bank Maryadit.Shivpuri.",
        "Nagrik Sahakari Bank Maryadit, Vidisha",
        "Paraspar Sahayak Coop Bank Maryadit., Indore",
        "Raj Rajeshwari Mahila Nagrik Sahakari Bank Maryadit., Shajapur",
        "Sadbhav Nagarik Sahakari Bank Maryadit.Chhatarpur",
        "Sadguru Nagari Sahakari Bank Maryadit.",
        "Samata Sahakari Bank Maryadit, Dewas",
        "Sanawad Nagrik Sahakari Bank Maryadit.",
        "Sardar Singh Nagarik Sahakari Bank Maryadit,",
        "Sehore Nagrik Sahakari Bank Maryadit.",
        "Shajapur Nagrik Sahakari Bank Maryadit,",
        "Shramik Nagrik Sahakari Bank Maryadit, Indore",
        "Shri Balaji Urban Co-operative Bank Ltd., Satna",
        "Shri Satya Sai Nagarik Sahakari Bank Maryadit., Bhopal",
        "Shri Vaibhav Lakshmi Mahila Nagarik Sahakari Bank MaryaditJhabua",
        "Shubhalaxmi Mahila Coop Bank Maryadit., Indore.",
        "Smriti Nagrik Sahakari Bank Maryadit., Mandsaur",
        "The Nagarik Shakari Bank Maryadit, Jhabua",
        "Transport Coop Bank Ltd., Indore",
        "Ujjain Audhyogik Vikas Nagrik Sahkari Bank Maryadit, Ujjain",
        "Ujjain Nagarik Sahakari Bank Maryadit, Ujjain",
        "Ujjain Paraspar Sahakari Bank Maryadit",
        "Vikramaditya Nagarik Sahakari Bank Maryadit, Ujjain",
        "Vivekanada Nagarik Sahakari Bank Maryad., Shujalpur",
        "Vyaparik Audhyogik Sahakari Bank Maryadit Indore",
        "Vyavasayik Evam Audhyogik Sah.Bk.Maryadit., Morena",
        "Balasore Coop.Urban Bank Ltd",
        "Berhampur Co-Operative Urban Bank Ltd.",
        "Cooperative Urban Bank Ltd, Parlakhemundi.",
        "Jeypore coop Urban Bank Ltd.",
        "Kendrapara Urban Coop Bank Ltd.",
        "Puri Urban Co-op. Bank Ltd.",
        "Urban Co op Bank Limited Cuttack.",
        "Urban Coop Bank Ltd, Rourkela.",
        "Utkal Coop Banking Soc Ltd., Bhubaneswar.",
        "Hissar Urban Coop Bank Limited.",
        "Imperial Urban cooprative Bank Ltd.Jalandhar",
        "The Citizens Urban Co op Bank Limited Jallandhar.",
        "Hindu Co-operative Bank Ltd., Pathankot",
        "The Karan Urban Cooperative Bank Ltd., Karnal",
        "The Kurukshetra Urban Co-op. Bank Ltd.",
        "The Nakodar Hindu Urban Coop. Bank Ltd.",
        "The Panchkula Urban Co-Op Bank Ltd.",
        "The Panipat Urban Co-Op Bank Ltd.",
        "The Postal & R.M.S.Employees' Coop Bank Ltd., Ambala Cantt",
        "The Sonepat urban Co-op. Bank Ltd",
        "Abiramam Co-Op Urban Bank Ltd.",
        "Ambasamudram Co-Op Urban Bank Ltd.",
        "Ammapet Urban Co-Op Bank Ltd.",
        "Arantangi Co-Op Town Bank Ltd.",
        "Arcot Co-operative Urban Bank Ltd.",
        "Ariyalur Co-Op Urban Bank Ltd.",
        "Arkonam Co-Op Urban Bank Ltd.",
        "Arni Co-Operative Town Bank Ltd., Arni",
        "Attur Town Co-Op Bank Ltd.",
        "B.Komarapalayam Co op Urban Bank Limited.",
        "Batlagundu Co op Urban Bank Limited.",
        "Bharat Heavy Electricals Employees Co op Bank Ltd.",
        "Bhavanikudal Co op Urban Bank Limited.",
        "Bhupathiraju Co op Credit Bank Limited.",
        "Big Kancheepuram Co op Town Bank Limited.",
        "Chengalpattu Coop.Urban Bank Ltd.",
        "Chennai Port Trust Employees Co-Op Bank Ltd.",
        "Chennimalai Co-operative Urban Bank Ltd.",
        "Chidambaram Coop. Urban Bank Ltd.",
        "Coimbatore City Coop. Bank Ltd.",
        "Coonoor Cooperative Urban Bank Ltd.",
        "Cordite Factory Coop. Bank Ltd.",
        "Cuddalore & Villipuram DCCB Employees Co-Op.Bank Ltd.",
        "Dalmiapuram Empl.s'Co-op. Bank Ltd.",
        "Dharapuram Coop Urban Bank Limited.",
        "Dharmapuri Co-op. Town Bank Ltd.",
        "Dindigul Urban Coop Bank Ltd.,",
        "Erode Co-operative Urban Bank Ltd.",
        "George Town Co op Bank Limited.",
        "Gobichettipalyam Co op Urban Bank Limited.",
        "Gudiyattam Co-Operative Urban Bank Ltd.,",
        "Ilayangudi Coop Urban Bank Ltd.",
        "Jolarpet Coop Urban Bank Ltd.",
        "Kallidaikurichi Coop Urban Bank Limited.",
        "Kamaraj coop Town Bank Ltd. Polur.",
        "Kamuthi Coop Urban Bank Ltd.",
        "Karaikudi Coop. Town Bank Ltd.",
        "Karuntattankudi Dravidian Coop Bank Ltd.",
        "Karur Town Coop. Bank Ltd.",
        "Kaveripatnam Coop Town Bank Ltd.",
        "Kodaikanal Coop. Urban Bank Ltd.",
        "Kovilpatti Co-operative Bank Ltd.",
        "Krishnagiri Urban Coop. Bank Ltd.",
        "Kulitalai Coop Urban Bank Limited.",
        "Kumbakonam Coop. Urban Bank Ltd.",
        "L.I.C.Employees' Coop Bank Ltd., Madras",
        "Lalgudi Coop Urban Bank Limited.",
        "Little Kancheepuram Coop Urban Bank Limited.",
        "Madura Sourashtra Co-Op Bank Ltd.",
        "Madurantakam Co-Op Urban Bank Ltd.",
        "Manapparai Town Co-Op Bank Ltd.",
        "Mannargudi Co-Op Urban Bank Ltd.",
        "Mayuram Co-Op Urban Bank Ltd.",
        "Melur Co-Op Urban Bank Ltd.",
        "Mettupalayam Co-Op Urban Bank Ltd.",
        "Mukkuperi Co-Op Urban Bank Ltd.",
        "Namakkal Coop. Urban Bank Ltd.",
        "Nazareth Urban Coop. Bank Ltd.",
        "Nellai Nagar Coop. Urban Bank Ltd.",
        "Nicholson Coop. Town Bank Ltd.",
        "Omalur Urban Co-Operative Bank Ltd.,",
        "Palani Coop. Urban Bank Ltd.",
        "Palayamkottai Urban Coop Bank Ltd.",
        "Pallikonda Coop. Urban Bank Ltd.",
        "Papanasam Coop. Urban Bank Ltd.",
        "Paramakudi Coop. Urban Bank Ltd.",
        "Pattukottai Coop. Urban Bank Ltd.",
        "Peoples Coop Bank Ltd., Nagarcoil",
        "Periyakulam Coop.Urban Bank Ltd.",
        "Pollachi Coop. Urban Bank Ltd.",
        "Pondicherry Coop. Urban Bank Ltd.",
        "Prakasapuram Coop. Urban Bank Ltd.",
        "Pudukottai Coop.Town Bank Ltd.",
        "Purasawalkam Coop. Bank Ltd.",
        "Rajapalayam Co-Op Urban Bank Ltd.",
        "Ramanathapuram Co-Op Urban Bank Ltd.",
        "Ranipet Town Co-Op Bank Ltd.",
        "Rasipuram Co-Op Urban Bank Ltd.",
        "Reserve Bank Employees'Coop Bank Ltd.",
        "Saidapet Co op Bank Ltd.",
        "Salem Urban Co op Bank Ltd.",
        "Sankari Co op Urban Bank Ltd.",
        "Satyamangalam Co op Urban Bank Ltd.",
        "Shevapet Urban Coop Bank Ltd.",
        "Sholavandan Urban Coop Bank Ltd.",
        "Sholinghur Co op Urban Bank Ltd.",
        "Sirkali Co op Urban Bank Ltd.",
        "Sivakasi Co op Urban Bank Ltd.",
        "Sri Kamalambika Co op Urban Bank Ltd.",
        "Sri Laxminarayana Coop Urban Bank"
    ],
    "Interest Rate Type": [
        "Fixed Interest Rate",
        "Floating Interest Rate"
    ],
    "Interest Rate": [
        "4%-5%",
        "5%-6%",
        "6%-7%",
        "7%-8%",
        "8%-9%",
        "9%-10%",
        "10%-11%",
        "11%-12%",
        "12%-13%",
        "13%-14%",
        "14%-15%"
    ],
    "Study Duration in months": [
        "6",
        "12",
        "18",
        "24",
        "30",
        "36",
        "42",
        "48"
    ],
    "Moratorium Period: Repayment Start": [
        "Course Duration + 6 Months",
        "Course Duration + 1 year",
        "Course Duration",
        "No moratourium"
    ],
    "Repayment Start": [
        "1 year after course completion",
        "6 months after course completion",
        "Immediate EMI",
        "After course completion"
    ],
    "Repayment Duration in Years": [
        "11",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12"
    ]

}
