export const riskAssessment = {
    "industry": [
        { "industry": "Technology & IT Services" },
        { "industry": "E-commerce & Retail" },
        { "industry": "Healthcare & Pharmaceuticals" },
        { "industry": "Finance & FinTech" },
        { "industry": "Real Estate & Property" },
        { "industry": "Education & EdTech" },
        { "industry": "Energy & Utilities" },
        { "industry": "Agriculture & Agribusiness" },
        { "industry": "Food & Beverage" },
        { "industry": "Entertainment & Media" },
        { "industry": "Hospitality & Tourism" },
        { "industry": "Transportation & Logistics" },
        { "industry": "Automotive & EV Industry" },
        { "industry": "Construction & Infrastructure" },
        { "industry": "Telecommunications" },
        { "industry": "Fashion & Apparel" },
        { "industry": "Beauty & Personal Care" },
        { "industry": "Legal Services" },
        { "industry": "Consulting & Business Services" },
        { "industry": "Insurance" },
        { "industry": "Cybersecurity" },
        { "industry": "Artificial Intelligence (AI)" },
        { "industry": "Waste Management & Recycling" },
        { "industry": "Gaming & Esports" },
        { "industry": "Aerospace & Space Technology" },
        { "industry": "Printing & Publishing" },
        { "industry": "Fitness & Wellness" },
        { "industry": "Home Services" },
        { "industry": "Human Resources & Staffing" },
        { "industry": "Blockchain & Cryptocurrency" },
        { "industry": "Biotechnology & Life Sciences" },
        { "industry": "Pet Care & Veterinary Services" },
        { "industry": "Luxury Goods & Jewelry" },
        { "industry": "Home Automation & Smart Tech" },
        { "industry": "Event Management & Wedding Planning" },
        { "industry": "Renewable Energy & Green Tech" },
        { "industry": "Drones & UAV Technology" },
        { "industry": "Textile & Fabric Manufacturing" },
        { "industry": "Luxury Travel & VIP Services" },
        { "industry": "Metaverse & Virtual Reality (VR)" },
        { "industry": "Elder Care & Assisted Living" },
        { "industry": "Augmented Reality (AR)" },
        { "industry": "3D Printing & Additive Manufacturing" },
        { "industry": "Water & Wastewater Supply" },
        { "industry": "Social Media & Influencer Marketing" },
        { "industry": "Ethical & Sustainable Businesses" },
        { "industry": "Agritech & Agribiosciences" },
        { "industry": "Self-Driving & Autonomous Tech" }
    ],
    "businessModel": [
        { "businessModel": "Subscription-based" },
        { "businessModel": "Freemium" },
        { "businessModel": "Direct Sales" },
        { "businessModel": "Marketplace" },
        { "businessModel": "Advertising-based" },
        { "businessModel": "On-demand" },
        { "businessModel": "Licensing" },
        { "businessModel": "Franchise" }
    ],
    "startupStage": [
        { "startupStage": "Ideation Stage" },
        { "startupStage": "Validation Stage" },
        { "startupStage": "Pre-Seed & Seed Stage" },
        { "startupStage": "Early-Stage Startup (Launch & Market Entry)" },
        { "startupStage": "Growth Stage (Scaling & Expansion)" },
        { "startupStage": "Maturity & Scaling (Sustainable Growth)" },
        { "startupStage": "Exit Strategies (Final Stage)" }
    ],
    "keyRisks": [
        { "keyRisks": "Market Risk" },
        { "keyRisks": "Financial Risk" },
        { "keyRisks": "Product Risk" },
        { "keyRisks": "Operational Risk" },
        { "keyRisks": "Legal & Compliance Risk" },
        { "keyRisks": "Competition Risk" },
        { "keyRisks": "Scalability Risk" },
        { "keyRisks": "Talent & HR Risk" },
        { "keyRisks": "Cybersecurity Risk" },
        { "keyRisks": "Technology Risk" },
        { "keyRisks": "Customer Retention Risk" },
        { "keyRisks": "Reputation Risk" },
        { "keyRisks": "Supply Chain Risk" },
        { "keyRisks": "Funding & Investment Risk" },
        { "keyRisks": "Economic Risk" },
        { "keyRisks": "Exit Strategy Risk" }
    ],
    "financialSituation": [
        { "financialSituation": "Bootstrapped" },
        { "financialSituation": "Pre-Revenue" },
        { "financialSituation": "Seed Funded" },
        { "financialSituation": "Break-Even" },
        { "financialSituation": "Burn Rate Crisis" },
        { "financialSituation": "High Growth & Revenue" },
        { "financialSituation": "Debt-Financed" },
        { "financialSituation": "Series A/B/C Funded" },
        { "financialSituation": "Profitability Achieved" },
        { "financialSituation": "Cash Flow Positive" },
        { "financialSituation": "Liquidity Crunch" },
        { "financialSituation": "Investor Dependence" },
        { "financialSituation": "Acquisition & Exit Strategy" },
        { "financialSituation": "Financial Crisis & Pivot" }
    ],
    "marketCompetition": [
        { "marketCompetition": "Low Competition" },
        { "marketCompetition": "Medium Competition" },
        { "marketCompetition": "High Competition" }
    ],
    "targetAudience": [
        { "targetAudience": "Children (0-12 years)" },
        { "targetAudience": "Teenagers (13-17 years)" },
        { "targetAudience": "Young Adults (18-25 years)" },
        { "targetAudience": "Middle-Aged Adults (36-55 years)" },
        { "targetAudience": "Seniors (55+ years)" },
        { "targetAudience": "Low-Income Consumers" },
        { "targetAudience": "Middle-Class Consumers" },
        { "targetAudience": "High-Income Consumers" },
        { "targetAudience": "Ultra-High-Net-Worth Individuals" },
        { "targetAudience": "Men" },
        { "targetAudience": "Women" },
        { "targetAudience": "Parents" },
        { "targetAudience": "Students" },
        { "targetAudience": "Working Professionals" },
        { "targetAudience": "Fitness Enthusiasts" },
        { "targetAudience": "Tech Lovers" },
        { "targetAudience": "Fashion & Beauty Seekers" },
        { "targetAudience": "Gamer Community" },
        { "targetAudience": "Environmentalists" },
        { "targetAudience": "Pet Owners" },
        { "targetAudience": "Impulsive Buyers" },
        { "targetAudience": "Loyal Customers" },
        { "targetAudience": "Discount Seekers" },
        { "targetAudience": "Quality-Oriented Buyers" },
        { "targetAudience": "Tech-Savvy Shoppers" },
        { "targetAudience": "Social Media Users" },
        { "targetAudience": "Mobile-First Consumers" },
        { "targetAudience": "Tech Enthusiasts" },
        { "targetAudience": "Remote Workers & Freelancers" }
    ],
    "budgetAllocation": [
        { "budgetAllocation": "₹1,00,000 - ₹5,00,000" },
        { "budgetAllocation": "₹5,00,000 - ₹10,00,000" },
        { "budgetAllocation": "₹10,00,000 - ₹15,00,000" },
        { "budgetAllocation": "₹15,00,000 - ₹20,00,000" },
        { "budgetAllocation": "₹20,00,000 - ₹30,00,000" },
        { "budgetAllocation": "₹30,00,000 - ₹40,00,000" },
        { "budgetAllocation": "₹40,00,000 - ₹50,00,000" },
        { "budgetAllocation": "₹50,00,000 - ₹75,00,000" },
        { "budgetAllocation": "₹75,00,000 - ₹1,00,00,000" },
        { "budgetAllocation": "₹1,00,00,000 - ₹1,50,00,000" },
        { "budgetAllocation": "₹1,50,00,000 - ₹2,00,00,000" },
        { "budgetAllocation": "₹2,00,00,000 - ₹2,50,00,000" },
        { "budgetAllocation": "₹2,50,00,000 - ₹3,00,00,000" },
        { "budgetAllocation": "₹3,00,00,000 - ₹4,00,00,000" },
        { "budgetAllocation": "₹4,00,00,000 - ₹4,50,00,000" },
        { "budgetAllocation": "₹4,50,00,000 - ₹5,00,00,000" },
        { "budgetAllocation": "₹5,00,00,000 - ₹5,50,00,000" },
        { "budgetAllocation": "₹6,00,00,000 - ₹7,00,00,000" },
        { "budgetAllocation": "₹7,00,00,000 - ₹8,00,00,000" },
        { "budgetAllocation": "₹8,00,00,000 - ₹9,00,00,000" },
        { "budgetAllocation": "₹9,00,00,000 - ₹10,00,00,000" }
    ],
    "geographicalFocus": [
        { "geographicalFocus": "City-Level" },
        { "geographicalFocus": "Regional-Level" },
        { "geographicalFocus": "Rural Market Focus" },
        { "geographicalFocus": "Single-Country Operations" },
        { "geographicalFocus": "International Presence" },
        { "geographicalFocus": "Global Brand Expansion" },
        { "geographicalFocus": "Borderless Digital Business" },
        { "geographicalFocus": "Tourism-Focused Markets" },
        { "geographicalFocus": "Expat & International Community Focus" },
        { "geographicalFocus": "Remote & Isolated Markets" }
    ]
};
