export const riskAssessment = {
    Industry: [
        { "Industry": "D Printing" },
        { "Industry": "Manufacturing" },
        { "Industry": "Prototyping" },
        { "Industry": "Aerospace" },
        { "Industry": "Aviation" },
        { "Industry": "Space" },
        { "Industry": "Agriculture" },
        { "Industry": "Agri-Tech" },
        { "Industry": "Artificial Intelligence" },
        { "Industry": "Robotics" },
        { "Industry": "Automation" },
        { "Industry": "Augmented Reality" },
        { "Industry": "Mixed Reality" },
        { "Industry": "Spatial Computing" },
        { "Industry": "Automotive" },
        { "Industry": "Mobility" },
        { "Industry": "Electric Vehicles" },
        { "Industry": "Autonomous Vehicles" },
        { "Industry": "Self-Driving" },
        { "Industry": "Banking" },
        { "Industry": "Finance" },
        { "Industry": "FinTech" },
        { "Industry": "Beauty" },
        { "Industry": "Skincare" },
        { "Industry": "Personal Care" },
        { "Industry": "Biotechnology" },
        { "Industry": "Genetics" },
        { "Industry": "Life Sciences" },
        { "Industry": "Blockchain" },
        { "Industry": "Cryptocurrency" },
        { "Industry": "Web3" },
        { "Industry": "Consulting" },
        { "Industry": "Construction" },
        { "Industry": "Engineering" },
        { "Industry": "Infrastructure" },
        { "Industry": "Cybersecurity" },
        { "Industry": "Data Privacy" },
        { "Industry": "IT Security" },
        { "Industry": "Drones" },
        { "Industry": "E-commerce" },
        { "Industry": "Retail" },
        { "Industry": "Marketplaces" },
        { "Industry": "EdTech" },
        { "Industry": "Digital Learning" },
        { "Industry": "Education" },
        { "Industry": "Training" },
        { "Industry": "Elderly Care" },
        { "Industry": "Healthcare" },
        { "Industry": "Assisted Living" },
        { "Industry": "Energy" },
        { "Industry": "Utilities" },
        { "Industry": "Power" },
        { "Industry": "Entertainment" },
        { "Industry": "Media" },
        { "Industry": "Broadcasting" },
        { "Industry": "Ethical Business" },
        { "Industry": "Sustainability" },
        { "Industry": "Event Planning" },
        { "Industry": "Weddings" },
        { "Industry": "Fashion" },
        { "Industry": "Apparel" },
        { "Industry": "Textiles" },
        { "Industry": "Fitness" },
        { "Industry": "Wellness" },
        { "Industry": "Food" },
        { "Industry": "Beverage" },
        { "Industry": "Consumer Goods" },
        { "Industry": "Gaming" },
        { "Industry": "Esports" },
        { "Industry": "Healthcare" },
        { "Industry": "Medical" },
        { "Industry": "Pharmaceuticals" },
        { "Industry": "Home Automation" },
        { "Industry": "IoT" },
        { "Industry": "Home Services" },
        { "Industry": "Hospitality" },
        { "Industry": "Tourism" },
        { "Industry": "Human Resources" },
        { "Industry": "Recruitment" },
        { "Industry": "Industrial" },
        { "Industry": "Technology" },
        { "Industry": "IT Services" },
        { "Industry": "Telecommunications" },
        { "Industry": "5G" },
        { "Industry": "Connectivity" },
        { "Industry": "Insurance" },
        { "Industry": "Risk Management" },
        { "Industry": "Legal" },
        { "Industry": "Compliance" },
        { "Industry": "Logistics" },
        { "Industry": "Transportation" },
        { "Industry": "Supply Chain" },
        { "Industry": "Luxury Goods" },
        { "Industry": "Jewelry" },
        { "Industry": "Luxury Travel" },
        { "Industry": "VIP Services" },
        { "Industry": "Metaverse" },
        { "Industry": "Digital Reality" },
        { "Industry": "Pet Care" },
        { "Industry": "Veterinary" },
        { "Industry": "Publishing" },
        { "Industry": "Printing" },
        { "Industry": "Real Estate" },
        { "Industry": "Renewable Energy" },
        { "Industry": "Green Tech" },
        { "Industry": "Smart Homes" },
        { "Industry": "Social Media" },
        { "Industry": "Influencer Marketing" },
        { "Industry": "Space Tourism" },
        { "Industry": "Astrobiology" },
        { "Industry": "Virtual Reality" },
        { "Industry": "Waste Management" },
        { "Industry": "Recycling" },
        { "Industry": "Water Purification" },
        { "Industry": "Finland" }
    ],    
  "businessModel": [
        { "businessModel": "B2B (Business-to-Business)" },
        { "businessModel": "B2C (Business-to-Consumer)" },
        { "businessModel": "B2B2C (Business-to-Business-to-Consumer)" },
        { "businessModel": "C2C (Consumer-to-Consumer)" },
        { "businessModel": "C2B (Consumer-to-Business)" },
        { "businessModel": "P2P (Peer-to-Peer)" },
        { "businessModel": "DTC (Direct-to-Consumer)" },
        { "businessModel": "B2G (Business-to-Government)" },
        { "businessModel": "G2B (Government-to-Business)" },
        { "businessModel": "G2C (Government-to-Consumer)" },
        { "businessModel": "C2G (Consumer-to-Government)" }
    ],
    "startupStage": [
        { "startupStage": "Ideation Stage" },
        { "startupStage": "Validation Stage" },
        { "startupStage": "Pre-Seed & Seed Stage" },
        { "startupStage": "Early-Stage Startup (Launch & Market Entry)" },
        { "startupStage": "Growth Stage (Scaling & Expansion)" },
        { "startupStage": "Maturity & Scaling (Sustainable Growth)" },
        { "startupStage": "Exit Strategies (Final Stage)" }
    ],
    "keyRisks": [
        { "keyRisks": "Market Risk" },
        { "keyRisks": "Financial Risk" },
        { "keyRisks": "Product Risk" },
        { "keyRisks": "Operational Risk" },
        { "keyRisks": "Legal & Compliance Risk" },
        { "keyRisks": "Competition Risk" },
        { "keyRisks": "Scalability Risk" },
        { "keyRisks": "Talent & HR Risk" },
        { "keyRisks": "Cybersecurity Risk" },
        { "keyRisks": "Technology Risk" },
        { "keyRisks": "Customer Retention Risk" },
        { "keyRisks": "Reputation Risk" },
        { "keyRisks": "Supply Chain Risk" },
        { "keyRisks": "Funding & Investment Risk" },
        { "keyRisks": "Economic Risk" },
        { "keyRisks": "Exit Strategy Risk" }
    ],
    "financialSituation": [
        { "financialSituation": "Bootstrapped" },
        { "financialSituation": "Pre-Revenue" },
        { "financialSituation": "Seed Funded" },
        { "financialSituation": "Break-Even" },
        { "financialSituation": "Burn Rate Crisis" },
        { "financialSituation": "High Growth & Revenue" },
        { "financialSituation": "Debt-Financed" },
        { "financialSituation": "Series A/B/C Funded" },
        { "financialSituation": "Profitability Achieved" },
        { "financialSituation": "Cash Flow Positive" },
        { "financialSituation": "Liquidity Crunch" },
        { "financialSituation": "Investor Dependence" },
        { "financialSituation": "Acquisition & Exit Strategy" },
        { "financialSituation": "Financial Crisis & Pivot" }
    ],
    "marketCompetition": [
        { "marketCompetition": "Low Competition" },
        { "marketCompetition": "Medium Competition" },
        { "marketCompetition": "High Competition" }
    ],
    "targetAudience": [
        { "targetAudience": "Children (0-12 years)" },
        { "targetAudience": "Teenagers (13-17 years)" },
        { "targetAudience": "Young Adults (18-25 years)" },
        { "targetAudience": "Middle-Aged Adults (36-55 years)" },
        { "targetAudience": "Seniors (55+ years)" },
        { "targetAudience": "Low-Income Consumers" },
        { "targetAudience": "Middle-Class Consumers" },
        { "targetAudience": "High-Income Consumers" },
        { "targetAudience": "Ultra-High-Net-Worth Individuals" },
        { "targetAudience": "Men" },
        { "targetAudience": "Women" },
        { "targetAudience": "Parents" },
        { "targetAudience": "Students" },
        { "targetAudience": "Working Professionals" },
        { "targetAudience": "Fitness Enthusiasts" },
        { "targetAudience": "Tech Lovers" },
        { "targetAudience": "Fashion & Beauty Seekers" },
        { "targetAudience": "Gamer Community" },
        { "targetAudience": "Environmentalists" },
        { "targetAudience": "Pet Owners" },
        { "targetAudience": "Impulsive Buyers" },
        { "targetAudience": "Loyal Customers" },
        { "targetAudience": "Discount Seekers" },
        { "targetAudience": "Quality-Oriented Buyers" },
        { "targetAudience": "Tech-Savvy Shoppers" },
        { "targetAudience": "Social Media Users" },
        { "targetAudience": "Mobile-First Consumers" },
        { "targetAudience": "Tech Enthusiasts" },
        { "targetAudience": "Remote Workers & Freelancers" }
    ],
    "budgetAllocation": [
        { "budgetAllocation": "₹1,00,000 - ₹5,00,000" },
        { "budgetAllocation": "₹5,00,000 - ₹10,00,000" },
        { "budgetAllocation": "₹10,00,000 - ₹15,00,000" },
        { "budgetAllocation": "₹15,00,000 - ₹20,00,000" },
        { "budgetAllocation": "₹20,00,000 - ₹30,00,000" },
        { "budgetAllocation": "₹30,00,000 - ₹40,00,000" },
        { "budgetAllocation": "₹40,00,000 - ₹50,00,000" },
        { "budgetAllocation": "₹50,00,000 - ₹75,00,000" },
        { "budgetAllocation": "₹75,00,000 - ₹1,00,00,000" },
        { "budgetAllocation": "₹1,00,00,000 - ₹1,50,00,000" },
        { "budgetAllocation": "₹1,50,00,000 - ₹2,00,00,000" },
        { "budgetAllocation": "₹2,00,00,000 - ₹2,50,00,000" },
        { "budgetAllocation": "₹2,50,00,000 - ₹3,00,00,000" },
        { "budgetAllocation": "₹3,00,00,000 - ₹4,00,00,000" },
        { "budgetAllocation": "₹4,00,00,000 - ₹4,50,00,000" },
        { "budgetAllocation": "₹4,50,00,000 - ₹5,00,00,000" },
        { "budgetAllocation": "₹5,00,00,000 - ₹5,50,00,000" },
        { "budgetAllocation": "₹6,00,00,000 - ₹7,00,00,000" },
        { "budgetAllocation": "₹7,00,00,000 - ₹8,00,00,000" },
        { "budgetAllocation": "₹8,00,00,000 - ₹9,00,00,000" },
        { "budgetAllocation": "₹9,00,00,000 - ₹10,00,00,000" }
    ],
    "geographicalFocus": [
        { "geographicalFocus": "City-Level" },
        { "geographicalFocus": "Regional-Level" },
        { "geographicalFocus": "Rural Market Focus" },
        { "geographicalFocus": "Single-Country Operations" },
        { "geographicalFocus": "International Presence" },
        { "geographicalFocus": "Global Brand Expansion" },
        { "geographicalFocus": "Borderless Digital Business" },
        { "geographicalFocus": "Tourism-Focused Markets" },
        { "geographicalFocus": "Expat & International Community Focus" },
        { "geographicalFocus": "Remote & Isolated Markets" }
    ],

};
